### Title:    Generate Unit Tests for Data with Potentially Problematic Variable Names
### Author:   Kyle M. Lang (Adapted from ./generate-tests.R)
### Created:  2024-03-22
### Modified: 2024-03-22

###-Setup--------------------------------------------------------------------------------------------------------------------###

setwd("~/software/jasp/modules/process/jaspProcess/")
getwd()

## Initialize the necessary subroutines:
source("./tests/test-generator-subroutines.R")

## Define some beautification strings for the resulting test scripts:
header    <- "### This code was automatically generated by 'generate-tests-for-bad-var-names.R'"
seperator <- paste(c("\n\n###", rep("-", 122), "###\n\n"), collapse = "")

## Define the potentially variable test parameters:
parms <- list()
parms$vars <- list(
  y       = "contNormal",
  numeric = list("contGamma", "contcor1", "contcor2", "debCollin1", "debMiss1"),
  factor  = list("facGender", "facExperim")
  )
parms$data <- "test.csv"

numMap <- list(
  "JaspProcess_Dependent_Encoded" = "contNormal",
  "JaspProcess_Independent_Encoded" = "contGamma",
  "JaspProcess_Mediator_Encoded" = "debCollin1",
  "JaspProcess_ModeratorW_Encoded" = "contcor1",
  "JaspProcess_ModeratorZ_Encoded" = "contcor2",
  "JaspProcess_Mediator_Encoded1" = "debCollin1",
  "JaspProcess_Mediator_Encoded2" = "contcor2",
  "JaspProcess_Mediator_Encoded3" = "debMiss1",
  "JaspProcess_Mediator_Encoded4" = "contcor1"
  )

 facMap <- list(
  "JaspProcess_Dependent_Encoded" = "contNormal",
  "JaspProcess_Independent_Encoded" = "facGender",
  "JaspProcess_Mediator_Encoded" = "debCollin1",
  "JaspProcess_ModeratorW_Encoded" = "facExperim",
  "JaspProcess_ModeratorZ_Encoded" = "contcor2",
  "JaspProcess_Mediator_Encoded1" = "debCollin1",
  "JaspProcess_Mediator_Encoded2" = "contcor2",
  "JaspProcess_Mediator_Encoded3" = "debMiss1",
  "JaspProcess_Mediator_Encoded4" = "contcor1"
  )

###-Tests 1------------------------------------------------------------------------------------------------------------------###

## Where are we saving these tests?
testsFile <- "tests/testthat/test-classic-process-hayes-models-with-bad-variable-names.R"

## Generate tests for continuous variables:
parms$type <- "continuous"
parms$map  <- numMap
numTests <- jaspProcess:::.procHardCodedModelNumbers() |> lapply(makeTestString, parms = parms)

## Generate tests for factor variables:
parms$type <- "factor"
parms$map  <- facMap
facTests <- jaspProcess:::.procHardCodedModelNumbers() |> lapply(makeTestString, parms = parms)

## Write tests to external script:
c(header, paste(numTests, facTests, sep = seperator)) |> writeLines(con = testsFile, sep = seperator)

###-Tests 2------------------------------------------------------------------------------------------------------------------###

customModels <- list(
  "one_confounder" = list(
    list(
      processDependent = "Y",
      processIndependent = "X",
      processType = "confounders",
      processVariable = "W"
    )
  ),
  "one_direct" = list(
    list(
      processDependent = "Y",
      processIndependent = "X",
      processType = "directs",
      processVariable = ""
    )
  ),
  "two_confounder" = list(
    list(
      processDependent = "Y",
      processIndependent = "X",
      processType = "confounders",
      processVariable = "W"
    ),
    list(
      processDependent = "Y",
      processIndependent = "X",
      processType = "confounders",
      processVariable = "Z"
    )
  ),
  "confounder_X_Y" = list(
    list(
      processDependent = "Y",
      processIndependent = "X",
      processType = "mediators",
      processVariable = "M"
    ),
    list(
      processDependent = "Y",
      processIndependent = "X",
      processType = "confounders",
      processVariable = "Z"
    )
  ),
  "confounder_X_M" = list(
    list(
      processDependent = "Y",
      processIndependent = "X",
      processType = "mediators",
      processVariable = "M"
    ),
    list(
      processDependent = "M",
      processIndependent = "X",
      processType = "confounders",
      processVariable = "Z"
    )
  ),
  "confounder_M_Y" = list(
    list(
      processDependent = "Y",
      processIndependent = "X",
      processType = "mediators",
      processVariable = "M"
    ),
    list(
      processDependent = "Y",
      processIndependent = "M",
      processType = "confounders",
      processVariable = "Z"
    )
  ),
  "confounder_moderator" = list(
    list(
      processDependent = "Y",
      processIndependent = "X",
      processType = "moderators",
      processVariable = "W"
    ),
    list(
      processDependent = "Y",
      processIndependent = "X",
      processType = "confounders",
      processVariable = "Z"
    )
  )
)

addProcessRelationshipsFromCustomModel <- function(k, options, replaceFun) {
  processRelationships <- customModels[[as.character(k)]]
  processRelationships <- lapply(processRelationships, function(row) {
    row <- lapply(row, replaceFun)
    return(row)
  })

  options$processModels[[1]][["processRelationships"]] <- processRelationships

  return(options)
}

replaceVariablesContinuousCustom <- function(v) {
  return(switch(v,
                "Y" = "contNormal",
                "X" = "contGamma",
                "M" = "debCollin1",
                "W" = "contcor1",
                "Z" = "contcor2",
                v
  ))
}

replaceVariablesFactorsCustom <- function(v) {
  return(switch(v,
                "Y" = "contNormal",
                "X" = "contGamma",
                "M" = "debCollin1",
                "W" = "facExperim",
                "Z" = "facGender",
                v
  ))
}

fileContext <- file("tests/testthat/test-classic-process-integration-custom-models.R")
header <- "# This code is automatically generated by 'generate-tests.R'"
testCode <- ""
for (k in names(customModels)) {
  opts <- getOptionsOneModel()
  opts <- addProcessRelationshipsFromCustomModel(k, opts, replaceVariablesContinuousCustom)
  testCode <- paste(testCode, captureCodeContinuous(k, opts), sep = "\n")
  opts <- getOptionsOneModel()
  opts <- addProcessRelationshipsFromCustomModel(k, opts, replaceVariablesFactorsCustom)
  testCode <- paste(testCode, captureCodeFactor(k, opts), sep = "\n")
}
writeLines(paste(header, testCode, sep = "\n\n"), fileContext)
close(fileContext)
