# Script for generating integration tests for all hard-coded models

source(testthat::test_path("helper-process-integration.R"))
source(testthat::test_path("generate-tests-helper.R"))


# Hayes models (classical) ------------------------------------------------

fileContext <- file(testthat::test_path("test-classic-process-integration-hayes-models.R"))
header <- "# This code is automatically generated by 'generate-tests.R'"
testCode <- ""

for (k in jaspProcess:::.procHardCodedModelNumbers()) {
  if (k %in% c(6, 80, 81)) next
  opts <- getOptionsOneModel()
  opts <- addProcessRelationshipsFromModelNumber(k, opts, replaceVariablesContinuous)
  testCode <- paste(testCode, captureCodeContinuous(k, opts), sep = "\n")
  opts <- getOptionsOneModel()
  opts <- addProcessRelationshipsFromModelNumber(k, opts, replaceVariablesFactors)
  testCode <- paste(testCode, captureCodeFactor(k, opts), sep = "\n")
}

writeLines(paste(header, testCode, sep = "\n\n"), fileContext)
close(fileContext)


# Custom models (classical) -----------------------------------------------

customModels <- list(
  "one_confounder" = list(
    list(
      processDependent = "Y",
      processIndependent = "X",
      processType = "confounders",
      processVariable = "W"
    )
  ),
  "one_direct" = list(
    list(
      processDependent = "Y",
      processIndependent = "X",
      processType = "directs",
      processVariable = ""
    )
  ),
  "two_confounder" = list(
    list(
      processDependent = "Y",
      processIndependent = "X",
      processType = "confounders",
      processVariable = "W"
    ),
    list(
      processDependent = "Y",
      processIndependent = "X",
      processType = "confounders",
      processVariable = "Z"
    )
  ),
  "confounder_X_Y" = list(
    list(
      processDependent = "Y",
      processIndependent = "X",
      processType = "mediators",
      processVariable = "M"
    ),
    list(
      processDependent = "Y",
      processIndependent = "X",
      processType = "confounders",
      processVariable = "Z"
    )
  ),
  "confounder_X_M" = list(
    list(
      processDependent = "Y",
      processIndependent = "X",
      processType = "mediators",
      processVariable = "M"
    ),
    list(
      processDependent = "M",
      processIndependent = "X",
      processType = "confounders",
      processVariable = "Z"
    )
  ),
  "confounder_M_Y" = list(
    list(
      processDependent = "Y",
      processIndependent = "X",
      processType = "mediators",
      processVariable = "M"
    ),
    list(
      processDependent = "Y",
      processIndependent = "M",
      processType = "confounders",
      processVariable = "Z"
    )
  ),
  "confounder_moderator" = list(
    list(
      processDependent = "Y",
      processIndependent = "X",
      processType = "moderators",
      processVariable = "W"
    ),
    list(
      processDependent = "Y",
      processIndependent = "X",
      processType = "confounders",
      processVariable = "Z"
    )
  )
)

fileContext <- file(testthat::test_path("test-classic-process-integration-custom-models.R"))
header <- "# This code is automatically generated by 'generate-tests.R'"
testCode <- ""
for (k in names(customModels)) {
  opts <- getOptionsOneModel()
  opts <- addProcessRelationshipsFromCustomModel(k, opts, replaceVariablesContinuousCustom)
  testCode <- paste(testCode, captureCodeContinuous(k, opts), sep = "\n")
  opts <- getOptionsOneModel()
  opts <- addProcessRelationshipsFromCustomModel(k, opts, replaceVariablesFactorsCustom)
  testCode <- paste(testCode, captureCodeFactor(k, opts), sep = "\n")
}
writeLines(paste(header, testCode, sep = "\n\n"), fileContext)
close(fileContext)


# Bad variables names (classical) -----------------------------------------

## Define some beautification strings for the resulting test scripts:
header    <- "### This code was automatically generated by 'generate-tests.R'"
seperator <- paste(c("\n\n###", rep("-", 122), "###\n\n"), collapse = "")

## Define the potentially variable test parameters:
parms <- list()
parms$vars <- list(
  y       = "M",
  numeric = list("W", "Y", "Z", "jasp", "mod"),
  factor  = list("s", "med")
)
parms$data <- testthat::test_path("data/badVarNames.csv")

## NOTE: The badVarNames.csv data contain a subset of the columns from test.csv with for following renaming:
## M       = contNormal
## W       = contGamma
## X       = contBinom
## Y       = contcor1
## Z       = contcor2
## s       = facGender
## med     = facExperim
## ss      = facFive
## mod     = debMiss1
## jasp    = debCollin1
## Encoded = debEqual1

numMap <- list(
  "JaspProcess_Dependent_Encoded" = "M",
  "JaspProcess_Independent_Encoded" = "W",
  "JaspProcess_Mediator_Encoded" = "jasp",
  "JaspProcess_ModeratorW_Encoded" = "Y",
  "JaspProcess_ModeratorZ_Encoded" = "Z",
  "JaspProcess_Mediator_Encoded1" = "jasp",
  "JaspProcess_Mediator_Encoded2" = "Z",
  "JaspProcess_Mediator_Encoded3" = "mod",
  "JaspProcess_Mediator_Encoded4" = "Y"
)

facMap <- list(
  "JaspProcess_Dependent_Encoded" = "M",
  "JaspProcess_Independent_Encoded" = "s",
  "JaspProcess_Mediator_Encoded" = "jasp",
  "JaspProcess_ModeratorW_Encoded" = "med",
  "JaspProcess_ModeratorZ_Encoded" = "Z",
  "JaspProcess_Mediator_Encoded1" = "jasp",
  "JaspProcess_Mediator_Encoded2" = "Z",
  "JaspProcess_Mediator_Encoded3" = "mod",
  "JaspProcess_Mediator_Encoded4" = "Y"
)

## Where are we saving these tests?
testsFile <- testthat::test_path("test-classic-process-hayes-models-with-bad-variable-names.R")

## Test a representative range of model numbers (we probably don't need to test them all here):
modelNumbers <- c(1:4, 10, 29, 82, 92)

## Make sure these model numbers are available:
modCheck <- modelNumbers %in% jaspProcess:::.procHardCodedModelNumbers() |> all()
if(!modCheck)
  stop("You've asked me to test a Haye's model number that isn't implemented.")

## Generate tests for continuous variables:
parms$type <- "continuous"
parms$map  <- numMap
numTests <- lapply(modelNumbers, makeTestString, parms = parms, testObjective = "works with bad variable names")

## Generate tests for factor variables:
parms$type <- "factor"
parms$map  <- facMap
facTests <- lapply(modelNumbers, makeTestString, parms = parms, testObjective = "works with bad variable names")

## Write tests to external script:
c(header, paste(numTests, facTests, sep = seperator)) |> writeLines(con = testsFile, sep = seperator)

# Hayes models (Bayesian) -------------------------------------------------

fileContext <- file(testthat::test_path("test-bayesian-process-integration.R"))
header <- "# This code is automatically generated by 'generate-tests.R'"
testCode <- ""

for (k in c(1:4, 10, 29, 82, 92)) {
  opts <- getOptionsOneModelBayes()
  opts <- addProcessRelationshipsFromModelNumber(k, opts, replaceVariablesContinuous)
  testCode <- paste(testCode, captureCodeContinuous(k, opts, "BayesianProcess"), sep = "\n")
  opts <- getOptionsOneModelBayes()
  opts <- addProcessRelationshipsFromModelNumber(k, opts, replaceVariablesFactors)
  testCode <- paste(testCode, captureCodeFactor(k, opts, "BayesianProcess"), sep = "\n")
}

writeLines(paste(header, testCode, sep = "\n\n"), fileContext)
close(fileContext)

