# This code is automatically generated by 'generate-tests.R'

context('Integration tests for variable input for models with confounder and direct paths')


context('Model number one_confounder - continuous')
 
options <- jaspTools::analysisOptions("ClassicProcess")
options$dependent <- "contNormal"
options$covariates <- list("contGamma", "contcor1", "contcor2", "debCollin1")
options$factors <- list("facGender", "facExperim")
options$pathPlotsLegend <- TRUE
options$errorCalculationMethod <- "standard"
options$naAction <- "fiml"
options$emulation <- "lavaan"
options$estimator <- "default"
options$moderationProbes <- list(list(probePercentile = 16, value = "16"), list(probePercentile = 50, 
    value = "50"), list(probePercentile = 84, value = "84"))
options$pathPlotsColorPalette <- "colorblind"
options$processModels <- list(list(conceptualPathPlot = TRUE, independentCovariances = TRUE, 
    inputType = "inputVariables", mediationEffects = TRUE, mediatorCovariances = TRUE, 
    modelNumber = 1, modelNumberCovariates = list(), modelNumberIndependent = "", 
    modelNumberMediators = list(), modelNumberModeratorW = "", 
    modelNumberModeratorZ = "", name = "Model 1", pathCoefficients = TRUE, 
    processRelationships = list(list(processDependent = "contNormal", 
        processIndependent = "contGamma", processType = "confounders", 
        processVariable = "contcor1")), residualCovariances = TRUE, 
    statisticalPathPlot = TRUE, totalEffects = TRUE, localTests = FALSE, 
    localTestType = "cis", localTestBootstrap = FALSE, localTestBootstrapSamples = 1000))
set.seed(1)
results <- jaspTools::runAnalysis("ClassicProcess", "debug", options)


test_that("Model fit table results match", {
	table <- results[["results"]][["modelFitTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(671.057567080859, 689.293758382775, 0, 0, 1, 100, 1, "", 0, 0
			))
})

test_that("Model numbers table results match", {
	table <- results[["results"]][["modelNumberTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list("Model 1", 4))
})

test_that("Residual covariances table results match", {
	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_covariancesTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(0.779896467881489, 1.37803301156572, 1.0789647397236, "contNormal",
			 "<unicode>", 1.53743684450092e-12, "contNormal", 0.152588656833048,
			 7.07106781144378, 1.63922475925008, 2.89641756877381, 2.26782116401194,
			 "contGamma", "<unicode>", 1.53743684450092e-12, "contGamma",
			 0.320718344683959, 7.07106781262135))
})

test_that("Mediation effects table results match", {
	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_mediationEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.0420059521849276, 0.367482204550967, 0.16273812618302, "contcor1",
			 "contNormal", "", "<unicode>", "", 0.119268458406113, 0.104463184008963,
			 1.55785148353373, -0.0271150029408878, 0.0385272160358304, 0.00570610654747128,
			 "contcor1", "contGamma", "contNormal", "<unicode>", "<unicode>",
			 0.733292476292754, 0.0167457717321583, 0.340749094084054))
})

test_that("Path coefficients table results match", {
	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_pathCoefficientsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.159257084877124, 0.111124625426377, -0.0240662297253736, "contGamma",
			 "<unicode>", 0.727159641785762, "contNormal", 0.0689761935515746,
			 -0.348906318052747, -0.0420059521849276, 0.367482204550967,
			 0.16273812618302, "contcor1", "<unicode>", 0.119268458406113,
			 "contNormal", 0.104463184008963, 1.55785148353373, -0.530272916905944,
			 0.056072627738489, -0.237100144583728, "contcor1", "<unicode>",
			 0.112943938944239, "contGamma", 0.149580693642703, -1.58509857662567
			))
})

test_that("Total effects table results match", {
	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_totalEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.0338982352424241, 0.370786700703406, 0.168444232730491, "Total",
			 0.102761008342432, 0.103237850067127, 1.63161314015127, -0.0420059521849276,
			 0.367482204550967, 0.16273812618302, "Total indirect", 0.119268458406113,
			 0.104463184008963, 1.55785148353373))
})

test_that("Conceptual path plot matches", {
	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_conceptPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "conceptual-path-plot-continuous-one_confounder")
})

test_that("Statistical path plot matches", {
	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_statPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "statistical-path-plot-continuous-one_confounder")
})


context('Model number one_confounder - factors')
 
options <- jaspTools::analysisOptions("ClassicProcess")
options$dependent <- "contNormal"
options$covariates <- list("contGamma", "contcor1", "contcor2", "debCollin1")
options$factors <- list("facGender", "facExperim")
options$pathPlotsLegend <- TRUE
options$errorCalculationMethod <- "standard"
options$naAction <- "fiml"
options$emulation <- "lavaan"
options$estimator <- "default"
options$moderationProbes <- list(list(probePercentile = 16, value = "16"), list(probePercentile = 50, 
    value = "50"), list(probePercentile = 84, value = "84"))
options$pathPlotsColorPalette <- "colorblind"
options$processModels <- list(list(conceptualPathPlot = TRUE, independentCovariances = TRUE, 
    inputType = "inputVariables", mediationEffects = TRUE, mediatorCovariances = TRUE, 
    modelNumber = 1, modelNumberCovariates = list(), modelNumberIndependent = "", 
    modelNumberMediators = list(), modelNumberModeratorW = "", 
    modelNumberModeratorZ = "", name = "Model 1", pathCoefficients = TRUE, 
    processRelationships = list(list(processDependent = "contNormal", 
        processIndependent = "contGamma", processType = "confounders", 
        processVariable = "facExperim")), residualCovariances = TRUE, 
    statisticalPathPlot = TRUE, totalEffects = TRUE, localTests = FALSE, 
    localTestType = "cis", localTestBootstrap = FALSE, localTestBootstrapSamples = 1000))
set.seed(1)
results <- jaspTools::runAnalysis("ClassicProcess", "debug", options)


test_that("Model fit table results match", {
	table <- results[["results"]][["modelFitTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(33074.7547574672, 33120.3751098071, 2.22044604925031e-12, 0, 1,
			 5000, 0, "", 2.22044604925031e-12, 0))
})

test_that("Model numbers table results match", {
	table <- results[["results"]][["modelNumberTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list("Model 1", 4))
})

test_that("Residual covariances table results match", {
	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_covariancesTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(1.06018008706752, 1.14668771529824, 1.10343390118288, "contNormal",
			 "<unicode>", 0, "contNormal", 0.0220686780249737, 49.9999999970182,
			 2.22105323705773, 2.40228475613878, 2.31166899659826, "contGamma",
			 "<unicode>", 0, "contGamma", 0.0462333799270229, 50.0000000053448
			))
})

test_that("Mediation effects table results match", {
	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_mediationEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(0.0246924587220919, 0.141488012780972, 0.0830902357515322, "facExperimexperimental",
			 "contNormal", "", "<unicode>", "", 0.00529200923127693, 0.0297953316949059,
			 2.78869980714926, -0.015529297268054, -0.00415202895501038,
			 -0.00984066311153217, "facExperimexperimental", "contGamma",
			 "contNormal", "<unicode>", "<unicode>", 0.00069763859701033,
			 0.00290241769817865, -3.39050548020965))
})

test_that("Path coefficients table results match", {
	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_pathCoefficientsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.0620868914130434, -0.0237864815309817, -0.0429366864720126,
			 "contGamma", "<unicode>", 1.11060473348967e-05, "contNormal",
			 0.00977069226377892, -4.39443647521106, 0.0246924587220919,
			 0.141488012780972, 0.0830902357515322, "facExperimexperimental",
			 "<unicode>", 0.00529200923127693, "contNormal", 0.0297953316949059,
			 2.78869980714926, 0.144904001511547, 0.313476181968453, 0.22919009174,
			 "facExperimexperimental", "<unicode>", 9.84731793884919e-08,
			 "contGamma", 0.0430038974661223, 5.32951907255737))
})

test_that("Total effects table results match", {
	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_totalEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(0.0149046189166239, 0.131594526363376, 0.07324957264, "Total",
			 0.0138685493330473, 0.0297683805333127, 2.4606502378599, 0.0246924587220919,
			 0.141488012780972, 0.0830902357515322, "Total indirect", 0.00529200923127693,
			 0.0297953316949059, 2.78869980714926))
})

test_that("Conceptual path plot matches", {
	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_conceptPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "conceptual-path-plot-factor-one_confounder")
})

test_that("Statistical path plot matches", {
	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_statPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "statistical-path-plot-factor-one_confounder")
})


context('Model number two_confounder - continuous')
 
options <- jaspTools::analysisOptions("ClassicProcess")
options$dependent <- "contNormal"
options$covariates <- list("contGamma", "contcor1", "contcor2", "debCollin1")
options$factors <- list("facGender", "facExperim")
options$pathPlotsLegend <- TRUE
options$errorCalculationMethod <- "standard"
options$naAction <- "fiml"
options$emulation <- "lavaan"
options$estimator <- "default"
options$moderationProbes <- list(list(probePercentile = 16, value = "16"), list(probePercentile = 50, 
    value = "50"), list(probePercentile = 84, value = "84"))
options$pathPlotsColorPalette <- "colorblind"
options$processModels <- list(list(conceptualPathPlot = TRUE, independentCovariances = TRUE, 
    inputType = "inputVariables", mediationEffects = TRUE, mediatorCovariances = TRUE, 
    modelNumber = 1, modelNumberCovariates = list(), modelNumberIndependent = "", 
    modelNumberMediators = list(), modelNumberModeratorW = "", 
    modelNumberModeratorZ = "", name = "Model 1", pathCoefficients = TRUE, 
    processRelationships = list(list(processDependent = "contNormal", 
        processIndependent = "contGamma", processType = "confounders", 
        processVariable = "contcor1"), list(processDependent = "contNormal", 
        processIndependent = "contGamma", processType = "confounders", 
        processVariable = "contcor2")), residualCovariances = TRUE, 
    statisticalPathPlot = TRUE, totalEffects = TRUE, localTests = FALSE, 
    localTestType = "cis", localTestBootstrap = FALSE, localTestBootstrapSamples = 1000))
set.seed(1)
results <- jaspTools::runAnalysis("ClassicProcess", "debug", options)


test_that("Model fit table results match", {
	table <- results[["results"]][["modelFitTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(1196.12854848421, 1232.60093108804, 0, 0, 1, 100, 1, "", 0, 0
			))
})

test_that("Model numbers table results match", {
	table <- results[["results"]][["modelNumberTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list("Model 1"))
})

test_that("Residual covariances table results match", {
	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_covariancesTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(0.424979180919744, 0.896763104121614, 0.660871142520679, "contcor2",
			 "<unicode>", 3.99655943894572e-08, "contcor1", 0.120355253189151,
			 5.4910037161573, 0.772432177868598, 1.36484403268291, 1.06863810527576,
			 "contNormal", "<unicode>", 1.53743684450092e-12, "contNormal",
			 0.151128250183979, 7.07106781144378, 1.63577445794209, 2.89032108123016,
			 2.26304776958613, "contGamma", "<unicode>", 1.53743684450092e-12,
			 "contGamma", 0.320043284770477, 7.07106781262135, 0.732634592963226,
			 1.29452395230351, 1.01357927263337, "contcor1", "<unicode>",
			 1.53743684450092e-12, "contcor1", 0.143341756219093, 7.07106777095817,
			 0.721541823114584, 1.27492365300028, 0.998232738057432, "contcor2",
			 "<unicode>", 1.53743684450092e-12, "contcor2", 0.141171428212636,
			 7.07106778401271))
})

test_that("Mediation effects table results match", {
	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_mediationEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.0183967830162192, 0.521461905534409, 0.251532561259095, "contcor1",
			 "contNormal", "", "<unicode>", "", 0.067792370251071, 0.137721583868113,
			 1.8263844649069, -0.0345845435803312, 0.0470351073738792, 0.00622528189677404,
			 "contcor1", "contGamma", "contNormal", "<unicode>", "<unicode>",
			 0.7649551805981, 0.0208217221331657, 0.298980163934575))
})

test_that("Path coefficients table results match", {
	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_pathCoefficientsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.155651256626207, 0.113717085937514, -0.0209670853443464, "contGamma",
			 "<unicode>", 0.760275337196381, "contNormal", 0.0687176766227503,
			 -0.305119241144496, -0.0183967830162192, 0.521461905534409,
			 0.251532561259095, "contcor1", "<unicode>", 0.067792370251071,
			 "contNormal", 0.137721583868113, 1.8263844649069, -0.404335782858585,
			 0.134221360435661, -0.135057211211462, "contcor2", "<unicode>",
			 0.325595679387153, "contNormal", 0.137389550915812, -0.983023893092285,
			 -0.685382138339048, 0.0915674240346943, -0.296907357152177,
			 "contcor1", "<unicode>", 0.134138263509527, "contGamma", 0.198205061037402,
			 -1.49798070542785, -0.299723108402101, 0.483175970242395, 0.091726430920147,
			 "contcor2", "<unicode>", 0.646041258390023, "contGamma", 0.199722822669167,
			 0.45926864889191))
})

test_that("Total effects table results match", {
	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_totalEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.00931723446549082, 0.524832920777229, 0.257757843155869, "Total",
			 0.0585458573430464, 0.136265298611614, 1.89158828977093, -0.0183967830162192,
			 0.521461905534409, 0.251532561259095, "Total indirect", 0.067792370251071,
			 0.137721583868113, 1.8263844649069))
})

test_that("Conceptual path plot matches", {
	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_conceptPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "conceptual-path-plot-continuous-two_confounder")
})

test_that("Statistical path plot matches", {
	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_statPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "statistical-path-plot-continuous-two_confounder")
})


context('Model number two_confounder - factors')
 
options <- jaspTools::analysisOptions("ClassicProcess")
options$dependent <- "contNormal"
options$covariates <- list("contGamma", "contcor1", "contcor2", "debCollin1")
options$factors <- list("facGender", "facExperim")
options$pathPlotsLegend <- TRUE
options$errorCalculationMethod <- "standard"
options$naAction <- "fiml"
options$emulation <- "lavaan"
options$estimator <- "default"
options$moderationProbes <- list(list(probePercentile = 16, value = "16"), list(probePercentile = 50, 
    value = "50"), list(probePercentile = 84, value = "84"))
options$pathPlotsColorPalette <- "colorblind"
options$processModels <- list(list(conceptualPathPlot = TRUE, independentCovariances = TRUE, 
    inputType = "inputVariables", mediationEffects = TRUE, mediatorCovariances = TRUE, 
    modelNumber = 1, modelNumberCovariates = list(), modelNumberIndependent = "", 
    modelNumberMediators = list(), modelNumberModeratorW = "", 
    modelNumberModeratorZ = "", name = "Model 1", pathCoefficients = TRUE, 
    processRelationships = list(list(processDependent = "contNormal", 
        processIndependent = "contGamma", processType = "confounders", 
        processVariable = "facExperim"), list(processDependent = "contNormal", 
        processIndependent = "contGamma", processType = "confounders", 
        processVariable = "facGender")), residualCovariances = TRUE, 
    statisticalPathPlot = TRUE, totalEffects = TRUE, localTests = FALSE, 
    localTestType = "cis", localTestBootstrap = FALSE, localTestBootstrapSamples = 1000))
set.seed(1)
results <- jaspTools::runAnalysis("ClassicProcess", "debug", options)


test_that("Model fit table results match", {
	table <- results[["results"]][["modelFitTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(23912.716668271, 23994.6072017236, 4.55457893622224e-12, 0, 1,
			 2564, 0, "", 4.55457893622224e-12, 0))
})

test_that("Model numbers table results match", {
	table <- results[["results"]][["modelNumberTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list("Model 1"))
})

test_that("Residual covariances table results match", {
	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_covariancesTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(0.0678662928171195, 0.0881399460794861, 0.0780031194483028, "facGenderm",
			 "<unicode>", 0, "facExperimexperimental", 0.00517194535774192,
			 15.0819689793396, 0.964298278001218, 1.07598309667668, 1.02014068733895,
			 "contNormal", "<unicode>", 0, "contNormal", 0.0284915487112048,
			 35.805027577801, 2.14401286536969, 2.3923319731885, 2.26817241927909,
			 "contGamma", "<unicode>", 0, "contGamma", 0.0633478752103413,
			 35.8050275837637, 0.236315020496248, 0.263684974960658, 0.249999997728453,
			 "facExperimexperimental", "<unicode>", 0, "facExperimexperimental",
			 0.00698225954157852, 35.8050279053268, 0.23631502030785, 0.263684974726257,
			 0.249999997517053, "facGenderm", "<unicode>", 0, "facGenderm",
			 0.0069822595298428, 35.8050279352309))
})

test_that("Mediation effects table results match", {
	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_mediationEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.0777273599874495, 0.087094964190169, 0.00468380210135975, "facExperimexperimental",
			 "contNormal", "", "<unicode>", "", 0.91130416369596, 0.0420472838985094,
			 0.111393689843681, -0.0120093993930699, 0.000237902017971967,
			 -0.00588574868754899, "facExperimexperimental", "contGamma",
			 "contNormal", "<unicode>", "<unicode>", 0.0595893322153731,
			 0.00312436899546294, -1.88381996367778))
})

test_that("Path coefficients table results match", {
	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_pathCoefficientsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.061364800040081, -0.00944762199995657, -0.0354062110200188,
			 "contGamma", "<unicode>", 0.00751107524515504, "contNormal",
			 0.0132444214408123, -2.67329238791175, -0.0777273599874495,
			 0.087094964190169, 0.00468380210135975, "facExperimexperimental",
			 "<unicode>", 0.91130416369596, "contNormal", 0.0420472838985094,
			 0.111393689843681, 0.396323768038625, 0.562182776442407, 0.479253272240516,
			 "facGenderm", "<unicode>", 0, "contNormal", 0.0423117490198945,
			 11.3267185437117, 0.0435198660581068, 0.288949975700514, 0.16623492087931,
			 "facExperimexperimental", "<unicode>", 0.00792969382999065,
			 "contGamma", 0.0626108723370247, 2.65504879063964, 0.270754763056346,
			 0.516184872702275, 0.39346981787931, "facGenderm", "<unicode>",
			 3.29188232228717e-10, "contGamma", 0.0626108723379232, 6.28436888334148
			))
})

test_that("Total effects table results match", {
	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_totalEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.0836146665909623, 0.0812107734185838, -0.00120194658618924,
			 "Total", 0.97719553269798, 0.0420480787681989, -0.0285850536195789,
			 -0.0777273599874495, 0.087094964190169, 0.00468380210135975,
			 "Total indirect", 0.91130416369596, 0.0420472838985094, 0.111393689843681
			))
})

test_that("Conceptual path plot matches", {
	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_conceptPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "conceptual-path-plot-factor-two_confounder")
})

test_that("Statistical path plot matches", {
	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_statPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "statistical-path-plot-factor-two_confounder")
})


context('Model number confounder_X_Y - continuous')
 
options <- jaspTools::analysisOptions("ClassicProcess")
options$dependent <- "contNormal"
options$covariates <- list("contGamma", "contcor1", "contcor2", "debCollin1")
options$factors <- list("facGender", "facExperim")
options$pathPlotsLegend <- TRUE
options$errorCalculationMethod <- "standard"
options$naAction <- "fiml"
options$emulation <- "lavaan"
options$estimator <- "default"
options$moderationProbes <- list(list(probePercentile = 16, value = "16"), list(probePercentile = 50, 
    value = "50"), list(probePercentile = 84, value = "84"))
options$pathPlotsColorPalette <- "colorblind"
options$processModels <- list(list(conceptualPathPlot = TRUE, independentCovariances = TRUE, 
    inputType = "inputVariables", mediationEffects = TRUE, mediatorCovariances = TRUE, 
    modelNumber = 1, modelNumberCovariates = list(), modelNumberIndependent = "", 
    modelNumberMediators = list(), modelNumberModeratorW = "", 
    modelNumberModeratorZ = "", name = "Model 1", pathCoefficients = TRUE, 
    processRelationships = list(list(processDependent = "contNormal", 
        processIndependent = "contGamma", processType = "mediators", 
        processVariable = "debCollin1"), list(processDependent = "contNormal", 
        processIndependent = "contGamma", processType = "confounders", 
        processVariable = "contcor2")), residualCovariances = TRUE, 
    statisticalPathPlot = TRUE, totalEffects = TRUE, localTests = FALSE, 
    localTestType = "cis", localTestBootstrap = FALSE, localTestBootstrapSamples = 1000))
set.seed(1)
results <- jaspTools::runAnalysis("ClassicProcess", "debug", options)


test_that("Model fit table results match", {
	table <- results[["results"]][["modelFitTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(463.152654417067, 491.809526462936, 0.200967982295878, 1, 1, 100,
			 0.653940650506637, 0.653940650506637, 0.200967982295878, 1
			))
})

test_that("Model numbers table results match", {
	table <- results[["results"]][["modelNumberTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list("Model 1"))
})

test_that("Residual covariances table results match", {
	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_covariancesTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(0.797840916249275, 1.40973983836071, 1.10379037730499, "contNormal",
			 "<unicode>", 1.53743684450092e-12, "contNormal", 0.156099532169473,
			 7.07106781144377, 0.00468047960523683, 0.00827014311689272,
			 0.00647531136106477, "debCollin1", "<unicode>", 1.53743684450092e-12,
			 "debCollin1", 0.000915747314739122, 7.07106781187719, 1.67248035663009,
			 2.95517833111984, 2.31382934387497, "contGamma", "<unicode>",
			 1.53743684450092e-12, "contGamma", 0.327224883877332, 7.07106781262502
			))
})

test_that("Mediation effects table results match", {
	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_mediationEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.176275917663598, 0.23731320938728, 0.030518645861841, "contcor2",
			 "contNormal", "", "", "<unicode>", "", "", 0.772389630563006,
			 0.105509369129539, 0.289250576641887, -0.0146865201087648, 0.0235011252675002,
			 0.00440730257936774, "contcor2", "contGamma", "contNormal",
			 "", "<unicode>", "<unicode>", "", 0.650976737427021, 0.00974192527961847,
			 0.452405705532197, -0.00284650352231386, 0.00231728159728851,
			 -0.000264610962512678, "contcor2", "contGamma", "debCollin1",
			 "contNormal", "<unicode>", "<unicode>", "<unicode>", 0.840799257584734,
			 0.00131731632834421, -0.200871238607722))
})

test_that("Path coefficients table results match", {
	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_pathCoefficientsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.179344122984299, 0.0952661457418632, -0.0420389886212179, "contGamma",
			 "<unicode>", 0.54844885058934, "contNormal", 0.0700549272568917,
			 -0.600086107677491, -2.83802376962913, 2.28501281087032, -0.276505479379406,
			 "debCollin1", "<unicode>", 0.832442407450254, "contNormal",
			 1.30692110184404, -0.211570139153206, -0.176275917663598, 0.23731320938728,
			 0.030518645861841, "contcor2", "<unicode>", 0.772389630563006,
			 "contNormal", 0.105509369129539, 0.289250576641887, -0.0194720938711713,
			 0.00121576385529671, -0.00912816500793728, "contGamma", "<unicode>",
			 0.0837015016290086, "debCollin1", 0.00527761170349332, -1.72960147899764,
			 -0.403237788230495, 0.193560880011857, -0.104838454109319, "contcor2",
			 "<unicode>", 0.491071197055343, "contGamma", 0.15224735580598,
			 -0.688606074991031))
})

test_that("Total effects table results match", {
	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_totalEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.171980601941184, 0.241303276898576, 0.034661337478696, "Total",
			 0.742339407118472, 0.105431498257032, 0.328756946943834, -0.176446788698357,
			 0.236954858497014, 0.0302540348993283, "Total indirect", 0.774209811472022,
			 0.105461541756948, 0.286872677900473))
})

test_that("Conceptual path plot matches", {
	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_conceptPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "conceptual-path-plot-continuous-confounder_X_Y")
})

test_that("Statistical path plot matches", {
	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_statPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "statistical-path-plot-continuous-confounder_X_Y")
})


context('Model number confounder_X_Y - factors')
 
options <- jaspTools::analysisOptions("ClassicProcess")
options$dependent <- "contNormal"
options$covariates <- list("contGamma", "contcor1", "contcor2", "debCollin1")
options$factors <- list("facGender", "facExperim")
options$pathPlotsLegend <- TRUE
options$errorCalculationMethod <- "standard"
options$naAction <- "fiml"
options$emulation <- "lavaan"
options$estimator <- "default"
options$moderationProbes <- list(list(probePercentile = 16, value = "16"), list(probePercentile = 50, 
    value = "50"), list(probePercentile = 84, value = "84"))
options$pathPlotsColorPalette <- "colorblind"
options$processModels <- list(list(conceptualPathPlot = TRUE, independentCovariances = TRUE, 
    inputType = "inputVariables", mediationEffects = TRUE, mediatorCovariances = TRUE, 
    modelNumber = 1, modelNumberCovariates = list(), modelNumberIndependent = "", 
    modelNumberMediators = list(), modelNumberModeratorW = "", 
    modelNumberModeratorZ = "", name = "Model 1", pathCoefficients = TRUE, 
    processRelationships = list(list(processDependent = "contNormal", 
        processIndependent = "contGamma", processType = "mediators", 
        processVariable = "debCollin1"), list(processDependent = "contNormal", 
        processIndependent = "contGamma", processType = "confounders", 
        processVariable = "facGender")), residualCovariances = TRUE, 
    statisticalPathPlot = TRUE, totalEffects = TRUE, localTests = FALSE, 
    localTestType = "cis", localTestBootstrap = FALSE, localTestBootstrapSamples = 1000))
set.seed(1)
results <- jaspTools::runAnalysis("ClassicProcess", "debug", options)


test_that("Model fit table results match", {
	table <- results[["results"]][["modelFitTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(21737.1399440223, 21808.8290691279, 4.77765150249665, 1, 1, 5000,
			 0.0288314151071502, 0.0288314151071503, 4.77765150249665, 1
			))
})

test_that("Model numbers table results match", {
	table <- results[["results"]][["modelNumberTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list("Model 1"))
})

test_that("Residual covariances table results match", {
	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_covariancesTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(1.00470148025984, 1.08668221466278, 1.04569184746131, "contNormal",
			 "<unicode>", 0, "contNormal", 0.0209138369504735, 49.999999997018,
			 0.00622148381994732, 0.0067291389022029, 0.00647531136107511,
			 "debCollin1", "<unicode>", 0, "debCollin1", 0.000129506227221495,
			 50.000000000003, 2.19128558260919, 2.37008814719909, 2.28068686490414,
			 "contGamma", "<unicode>", 0, "contGamma", 0.0456137372932041,
			 50.0000000053478))
})

test_that("Mediation effects table results match", {
	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_mediationEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(0.433538587814001, 0.548061529562611, 0.490800058688306, "facGenderm",
			 "contNormal", "", "", "<unicode>", "", "", 0, 0.0292155730033696,
			 16.7992617715113, -0.0367766243593456, -0.0174765319687376,
			 -0.0271265781640416, "facGenderm", "contGamma", "contNormal",
			 "", "<unicode>", "<unicode>", "", 3.59814844586026e-08, 0.00492358342878865,
			 -5.50951934833275, -0.000723712683687103, 0.00199843322914707,
			 0.000637360272729985, "facGenderm", "contGamma", "debCollin1",
			 "contNormal", "<unicode>", "<unicode>", "<unicode>", 0.358719573386505,
			 0.000694437738220222, 0.917807655965644))
})

test_that("Path coefficients table results match", {
	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_pathCoefficientsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.0836056710361881, -0.0455477830378536, -0.0645767270370208,
			 "contGamma", "<unicode>", 2.90427681903793e-11, "contNormal",
			 0.00970882329944075, -6.6513443540311, -0.518624752729228, 0.186185330077073,
			 -0.166219711326077, "debCollin1", "<unicode>", 0.355246450057907,
			 "contNormal", 0.179801794411977, -0.924460803462397, 0.433538587814001,
			 0.548061529562611, 0.490800058688306, "facGenderm", "<unicode>",
			 0, "contNormal", 0.0292155730033696, 16.7992617715113, -0.0105910174565992,
			 -0.00766531255927537, -0.00912816500793726, "contGamma", "<unicode>",
			 0, "debCollin1", 0.000746367004802478, -12.230129345486, 0.336348042227948,
			 0.503786768212052, 0.42006740522, "facGenderm", "<unicode>",
			 0, "contGamma", 0.0427147456037046, 9.83424808653356))
})

test_that("Total effects table results match", {
	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_totalEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(0.407350494995409, 0.52127118659858, 0.464310840796994, "Total",
			 0, 0.0290619349390505, 15.9765976274725, 0.434201538083914,
			 0.548673299838158, 0.491437418961036, "Total indirect", 0, 0.029202516642444,
			 16.8285981985115))
})

test_that("Conceptual path plot matches", {
	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_conceptPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "conceptual-path-plot-factor-confounder_X_Y")
})

test_that("Statistical path plot matches", {
	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_statPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "statistical-path-plot-factor-confounder_X_Y")
})


context('Model number confounder_X_M - continuous')
 
options <- jaspTools::analysisOptions("ClassicProcess")
options$dependent <- "contNormal"
options$covariates <- list("contGamma", "contcor1", "contcor2", "debCollin1")
options$factors <- list("facGender", "facExperim")
options$pathPlotsLegend <- TRUE
options$errorCalculationMethod <- "standard"
options$naAction <- "fiml"
options$emulation <- "lavaan"
options$estimator <- "default"
options$moderationProbes <- list(list(probePercentile = 16, value = "16"), list(probePercentile = 50, 
    value = "50"), list(probePercentile = 84, value = "84"))
options$pathPlotsColorPalette <- "colorblind"
options$processModels <- list(list(conceptualPathPlot = TRUE, independentCovariances = TRUE, 
    inputType = "inputVariables", mediationEffects = TRUE, mediatorCovariances = TRUE, 
    modelNumber = 1, modelNumberCovariates = list(), modelNumberIndependent = "", 
    modelNumberMediators = list(), modelNumberModeratorW = "", 
    modelNumberModeratorZ = "", name = "Model 1", pathCoefficients = TRUE, 
    processRelationships = list(list(processDependent = "contNormal", 
        processIndependent = "contGamma", processType = "mediators", 
        processVariable = "debCollin1"), list(processDependent = "debCollin1", 
        processIndependent = "contGamma", processType = "confounders", 
        processVariable = "contcor2")), residualCovariances = TRUE, 
    statisticalPathPlot = TRUE, totalEffects = TRUE, localTests = FALSE, 
    localTestType = "cis", localTestBootstrap = FALSE, localTestBootstrapSamples = 1000))
set.seed(1)
results <- jaspTools::runAnalysis("ClassicProcess", "debug", options)


test_that("Model fit table results match", {
	table <- results[["results"]][["modelFitTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(463.035317350457, 491.692189396326, 0.0836309156863418, 1, 1,
			 100, 0.772435905091371, 0.772435905091371, 0.0836309156863418,
			 1))
})

test_that("Model numbers table results match", {
	table <- results[["results"]][["modelNumberTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list("Model 1"))
})

test_that("Residual covariances table results match", {
	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_covariancesTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(0.798508437001207, 1.41091930982899, 1.1047138734151, "contNormal",
			 "<unicode>", 1.53743684450092e-12, "contNormal", 0.156230134241854,
			 7.07106781144369, 0.00467108278527448, 0.00825353946673517,
			 0.00646231112600483, "debCollin1", "<unicode>", 1.53743684450092e-12,
			 "debCollin1", 0.00091390880386544, 7.07106781187799, 1.67248035662978,
			 2.95517833112015, 2.31382934387497, "contGamma", "<unicode>",
			 1.53743684450092e-12, "contGamma", 0.32722488387749, 7.07106781262161
			))
})

test_that("Mediation effects table results match", {
	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_mediationEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.0147847276314926, 0.0238549732319836, 0.0045351228002455, "contcor2",
			 "contGamma", "contNormal", "", "<unicode>", "<unicode>", "",
			 0.645458778034415, 0.00985724767604437, 0.460080029364283, -0.0110675944619271,
			 0.0091897190934133, -0.000938937684256923, "contcor2", "debCollin1",
			 "contNormal", "", "<unicode>", "<unicode>", "", 0.855825363710885,
			 0.00516777698853845, -0.181690828830149, -0.00276416621173955,
			 0.00227622599093872, -0.000243970110400414, "contcor2", "contGamma",
			 "debCollin1", "contNormal", "<unicode>", "<unicode>", "<unicode>",
			 0.849515790919551, 0.00128583796499227, -0.189736278631251
			))
})

test_that("Path coefficients table results match", {
	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_pathCoefficientsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.180371895866263, 0.0938554961582594, -0.0432581998540016, "contGamma",
			 "<unicode>", 0.53634340051597, "contNormal", 0.0699572528341319,
			 -0.618351894928843, -2.81958314196223, 2.30044870969042, -0.259567216135903,
			 "debCollin1", "<unicode>", 0.842476879751365, "contNormal",
			 1.30615457529802, -0.198726261841313, -0.0193233386536883, 0.00139268298709497,
			 -0.00896532783329667, "contGamma", "<unicode>", 0.0898030262925182,
			 "debCollin1", 0.00528479650753499, -1.69643766236108, -0.0121898218443532,
			 0.0194244618596418, 0.00361732000764426, "contcor2", "<unicode>",
			 0.653778061698369, "debCollin1", 0.00806501648840603, 0.448519852729922,
			 -0.403237788230758, 0.19356088001212, -0.104838454109319, "contcor2",
			 "<unicode>", 0.491071197055724, "contGamma", 0.152247355806114,
			 -0.688606074990426))
})

test_that("Total effects table results match", {
	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_totalEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.0178966078892263, 0.0246010379004026, 0.00335221500558816,
			 "Total", 0.757166364046536, 0.010841435384743, 0.309203983294102,
			 -0.013566230336357, 0.0112004147470423, -0.00118290779465734,
			 "Total indirect", 0.851484913606803, 0.00631813780221356, -0.187224120727931
			))
})

test_that("Conceptual path plot matches", {
	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_conceptPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "conceptual-path-plot-continuous-confounder_X_M")
})

test_that("Statistical path plot matches", {
	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_statPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "statistical-path-plot-continuous-confounder_X_M")
})


context('Model number confounder_X_M - factors')
 
options <- jaspTools::analysisOptions("ClassicProcess")
options$dependent <- "contNormal"
options$covariates <- list("contGamma", "contcor1", "contcor2", "debCollin1")
options$factors <- list("facGender", "facExperim")
options$pathPlotsLegend <- TRUE
options$errorCalculationMethod <- "standard"
options$naAction <- "fiml"
options$emulation <- "lavaan"
options$estimator <- "default"
options$moderationProbes <- list(list(probePercentile = 16, value = "16"), list(probePercentile = 50, 
    value = "50"), list(probePercentile = 84, value = "84"))
options$pathPlotsColorPalette <- "colorblind"
options$processModels <- list(list(conceptualPathPlot = TRUE, independentCovariances = TRUE, 
    inputType = "inputVariables", mediationEffects = TRUE, mediatorCovariances = TRUE, 
    modelNumber = 1, modelNumberCovariates = list(), modelNumberIndependent = "", 
    modelNumberMediators = list(), modelNumberModeratorW = "", 
    modelNumberModeratorZ = "", name = "Model 1", pathCoefficients = TRUE, 
    processRelationships = list(list(processDependent = "contNormal", 
        processIndependent = "contGamma", processType = "mediators", 
        processVariable = "debCollin1"), list(processDependent = "debCollin1", 
        processIndependent = "contGamma", processType = "confounders", 
        processVariable = "facGender")), residualCovariances = TRUE, 
    statisticalPathPlot = TRUE, totalEffects = TRUE, localTests = FALSE, 
    localTestType = "cis", localTestBootstrap = FALSE, localTestBootstrapSamples = 1000))
set.seed(1)
results <- jaspTools::runAnalysis("ClassicProcess", "debug", options)


test_that("Model fit table results match", {
	table <- results[["results"]][["modelFitTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(22006.900502578, 22078.5896276835, 274.538210058115, 1, 1, 5000,
			 1.16374025275942e-61, 0, 274.538210058115, 1))
})

test_that("Model numbers table results match", {
	table <- results[["results"]][["modelNumberTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list("Model 1"))
})

test_that("Residual covariances table results match", {
	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_covariancesTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(1.06140988531022, 1.14801786151998, 1.1047138734151, "contNormal",
			 "<unicode>", 0, "contNormal", 0.0220942774696161, 49.999999997026,
			 0.00621554184295394, 0.00672271207707478, 0.00646912696001436,
			 "debCollin1", "<unicode>", 0, "debCollin1", 0.000129382539200041,
			 50.0000000000952, 2.19128558260923, 2.37008814719904, 2.28068686490414,
			 "contGamma", "<unicode>", 0, "contGamma", 0.0456137372931794,
			 50.0000000053748))
})

test_that("Mediation effects table results match", {
	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_mediationEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.027085611963009, -0.00925710757130837, -0.0181713597671587,
			 "facGenderm", "contGamma", "contNormal", "", "<unicode>", "<unicode>",
			 "", 6.46093570770834e-05, 0.00454817142874298, -3.9953110941073,
			 -0.000857709880850443, 0.00346457593234885, 0.00130343302574921,
			 "facGenderm", "debCollin1", "contNormal", "", "<unicode>", "<unicode>",
			 "", 0.237166986948733, 0.0011026441932844, 1.18209757389346,
			 -0.00040635584874525, 0.00234748159528164, 0.000970562873268195,
			 "facGenderm", "contGamma", "debCollin1", "contNormal", "<unicode>",
			 "<unicode>", "<unicode>", 0.167112991099118, 0.000702522461062756,
			 1.38153998919829))
})

test_that("Path coefficients table results match", {
	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_pathCoefficientsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.0626490047023849, -0.0238673950056185, -0.0432581998540017,
			 "contGamma", "<unicode>", 1.22883503528293e-05, "contNormal",
			 0.00989344957424494, -4.37240818072327, -0.621608140347748,
			 0.102473708075942, -0.259567216135903, "debCollin1", "<unicode>",
			 0.15995977081938, "contNormal", 0.184718151490322, -1.40520687350805,
			 -0.0103775557865125, -0.00742510211850606, -0.00890132895250926,
			 "contGamma", "<unicode>", 0, "debCollin1", 0.00075319079618171,
			 -11.8181594857962, -0.00952325675091811, -0.000519868456902911,
			 -0.00502156260391051, "facGenderm", "<unicode>", 0.0287932104321471,
			 "debCollin1", 0.00229682493276223, -2.1863062057026, 0.336348042227534,
			 0.503786768212466, 0.42006740522, "facGenderm", "<unicode>",
			 0, "contGamma", 0.0427147456039159, 9.83424808648492))
})

test_that("Total effects table results match", {
	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_totalEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.0248803182473269, -0.00691440948895571, -0.0158973638681413,
			 "Total", 0.000523181013263985, 0.00458322420720073, -3.4685983380793,
			 -0.00110783982746352, 0.00565583162549832, 0.0022739958990174,
			 "Total indirect", 0.187534278593405, 0.00172545809675913, 1.31790850400167
			))
})

test_that("Conceptual path plot matches", {
	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_conceptPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "conceptual-path-plot-factor-confounder_X_M")
})

test_that("Statistical path plot matches", {
	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_statPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "statistical-path-plot-factor-confounder_X_M")
})


context('Model number confounder_moderator - continuous')
 
options <- jaspTools::analysisOptions("ClassicProcess")
options$dependent <- "contNormal"
options$covariates <- list("contGamma", "contcor1", "contcor2", "debCollin1")
options$factors <- list("facGender", "facExperim")
options$pathPlotsLegend <- TRUE
options$errorCalculationMethod <- "standard"
options$naAction <- "fiml"
options$emulation <- "lavaan"
options$estimator <- "default"
options$moderationProbes <- list(list(probePercentile = 16, value = "16"), list(probePercentile = 50, 
    value = "50"), list(probePercentile = 84, value = "84"))
options$pathPlotsColorPalette <- "colorblind"
options$processModels <- list(list(conceptualPathPlot = TRUE, independentCovariances = TRUE, 
    inputType = "inputVariables", mediationEffects = TRUE, mediatorCovariances = TRUE, 
    modelNumber = 1, modelNumberCovariates = list(), modelNumberIndependent = "", 
    modelNumberMediators = list(), modelNumberModeratorW = "", 
    modelNumberModeratorZ = "", name = "Model 1", pathCoefficients = TRUE, 
    processRelationships = list(list(processDependent = "contNormal", 
        processIndependent = "contGamma", processType = "moderators", 
        processVariable = "contcor1"), list(processDependent = "contNormal", 
        processIndependent = "contGamma", processType = "confounders", 
        processVariable = "contcor2")), residualCovariances = TRUE, 
    statisticalPathPlot = TRUE, totalEffects = TRUE, localTests = FALSE, 
    localTestType = "cis", localTestBootstrap = FALSE, localTestBootstrapSamples = 1000))
set.seed(1)
results <- jaspTools::runAnalysis("ClassicProcess", "debug", options)


test_that("Model fit table results match", {
	table <- results[["results"]][["modelFitTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(1673.68391243887, 1715.36663541468, 115.460937786159, 4, 1, 100,
			 4.97553047047225e-24, 0, 115.460937786159, 4))
})

test_that("Model numbers table results match", {
	table <- results[["results"]][["modelNumberTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list("Model 1", 14))
})

test_that("Residual covariances table results match", {
	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_covariancesTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(0.424980219011524, 0.896764687995005, 0.660872453503265, "contcor2",
			 "<unicode>", 3.99645667670256e-08, "contcor1", 0.120355392421712,
			 5.49100825651119, 0.770797942166486, 1.36195643069315, 1.06637718642982,
			 "contNormal", "<unicode>", 1.53743684450092e-12, "contNormal",
			 0.150808508010772, 7.07106780973954, 1.67248035662507, 2.95517833112486,
			 2.31382934387497, "contGamma", "<unicode>", 1.53743684450092e-12,
			 "contGamma", 0.327224883879895, 7.07106781256964, 4.72565699744065,
			 8.34996570286764, 6.53781135015415, "contGamma:contcor1", "<unicode>",
			 1.53743684450092e-12, "contGamma:contcor1", 0.924585536779011,
			 7.07107248608927, 0.732635023334987, 1.29452545342238, 1.01358023837868,
			 "contcor1", "<unicode>", 1.53743684450092e-12, "contcor1", 0.143342029373884,
			 7.07106103357113, 0.721541374173015, 1.27492208712788, 0.998231730650445,
			 "contcor2", "<unicode>", 1.53743684450092e-12, "contcor2", 0.141171143276064,
			 7.07107492002366))
})

test_that("Mediation effects table results match", {
	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_mediationEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.0550996972137133, 0.673135755563669, 0.309018029174978, "contcor1",
			 "contNormal", "<unicode>", 0.0962374576019276, 0.185777763908319,
			 1.66337468313741))
})

test_that("Path coefficients table results match", {
	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_pathCoefficientsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.157439639758971, 0.112046361719874, -0.0226966390195488, "contGamma",
			 "<unicode>", 0.741291147947004, "contNormal", 0.0687476922036619,
			 -0.330144013450096, -0.0550996972137133, 0.673135755563669,
			 0.309018029174978, "contcor1", "<unicode>", 0.0962374576019276,
			 "contNormal", 0.185777763908319, 1.66337468313741, -0.39652857777913,
			 0.156057758066743, -0.120235409856194, "contcor2", "<unicode>",
			 0.393701453426022, "contNormal", 0.140968492330625, -0.852923996478555,
			 -0.172199266907274, 0.106681531269352, -0.0327588678189609,
			 "contGamma:contcor1", "<unicode>", 0.645188778617887, "contNormal",
			 0.0711443680538017, -0.460456234486299, -0.403237788220294,
			 0.193560880001656, -0.104838454109319, "contcor2", "<unicode>",
			 0.491071197040525, "contGamma", 0.152247355800775, -0.688606075014572
			))
})

test_that("Total effects table results match", {
	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_totalEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.0550996972137133, 0.673135755563669, 0.309018029174978, "Total",
			 0.0962374576019276, 0.185777763908319, 1.66337468313741, -0.0550996972137133,
			 0.673135755563669, 0.309018029174978, "Total indirect", 0.0962374576019276,
			 0.185777763908319, 1.66337468313741))
})

test_that("Conceptual path plot matches", {
	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_conceptPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "conceptual-path-plot-continuous-confounder_moderator")
})

test_that("Statistical path plot matches", {
	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_statPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "statistical-path-plot-continuous-confounder_moderator")
})


context('Model number confounder_moderator - factors')
 
options <- jaspTools::analysisOptions("ClassicProcess")
options$dependent <- "contNormal"
options$covariates <- list("contGamma", "contcor1", "contcor2", "debCollin1")
options$factors <- list("facGender", "facExperim")
options$pathPlotsLegend <- TRUE
options$errorCalculationMethod <- "standard"
options$naAction <- "fiml"
options$emulation <- "lavaan"
options$estimator <- "default"
options$moderationProbes <- list(list(probePercentile = 16, value = "16"), list(probePercentile = 50, 
    value = "50"), list(probePercentile = 84, value = "84"))
options$pathPlotsColorPalette <- "colorblind"
options$processModels <- list(list(conceptualPathPlot = TRUE, independentCovariances = TRUE, 
    inputType = "inputVariables", mediationEffects = TRUE, mediatorCovariances = TRUE, 
    modelNumber = 1, modelNumberCovariates = list(), modelNumberIndependent = "", 
    modelNumberMediators = list(), modelNumberModeratorW = "", 
    modelNumberModeratorZ = "", name = "Model 1", pathCoefficients = TRUE, 
    processRelationships = list(list(processDependent = "contNormal", 
        processIndependent = "contGamma", processType = "moderators", 
        processVariable = "facExperim"), list(processDependent = "contNormal", 
        processIndependent = "contGamma", processType = "confounders", 
        processVariable = "facGender")), residualCovariances = TRUE, 
    statisticalPathPlot = TRUE, totalEffects = TRUE, localTests = FALSE, 
    localTestType = "cis", localTestBootstrap = FALSE, localTestBootstrapSamples = 1000))
set.seed(1)
results <- jaspTools::runAnalysis("ClassicProcess", "debug", options)


test_that("Model fit table results match", {
	table <- results[["results"]][["modelFitTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(64941.4042502515, 65045.6793413141, 6677.32310182435, 4, 1, 5000,
			 0, 0, 6677.32310182435, 4))
})

test_that("Model numbers table results match", {
	table <- results[["results"]][["modelNumberTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list("Model 1", 14))
})

test_that("Residual covariances table results match", {
	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_covariancesTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(0.0329823346594564, 0.0470176447661279, 0.0399999897127922, "facGenderm",
			 "<unicode>", 0, "facExperimexperimental", 0.00358050204426719,
			 11.1716148233561, 0.968625841347474, 1.04766290797544, 1.00814437466146,
			 "contNormal", "<unicode>", 0, "contNormal", 0.0201628874947199,
			 49.9999999963032, 2.19128558261251, 2.37008814719577, 2.28068686490414,
			 "contGamma", "<unicode>", 0, "contGamma", 0.0456137372915091,
			 50.0000000072057, 2.05123341412772, 2.21860811897046, 2.13492076654909,
			 "contGamma:facExperimexperimental", "<unicode>", 0, "contGamma:facExperimexperimental",
			 0.0426984133797779, 50.000002284867, 0.240200158724482, 0.25979979493696,
			 0.249999976830721, "facExperimexperimental", "<unicode>", 0,
			 "facExperimexperimental", 0.004999999073217, 50.0000046339751,
			 0.240200157361428, 0.259799793341984, 0.249999975351706, "facGenderm",
			 "<unicode>", 0, "facGenderm", 0.00499999901405202, 50.0000049298219
			))
})

test_that("Mediation effects table results match", {
	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_mediationEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.619417420269258, -0.429267635860784, -0.524342528065021, "facExperimexperimental",
			 "contNormal", "<unicode>", 0, 0.0485084894182627, -10.8092940916774
			))
})

test_that("Path coefficients table results match", {
	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_pathCoefficientsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.19839138233443, -0.149699317871868, -0.174045350103149, "contGamma",
			 "<unicode>", 0, "contNormal", 0.012421673267121, -14.0114255431135,
			 -0.619417420269258, -0.429267635860784, -0.524342528065021,
			 "facExperimexperimental", "<unicode>", 0, "contNormal", 0.0485084894182627,
			 -10.8092940916774, 0.454487785532165, 0.568357318512357, 0.511422552022261,
			 "facGenderm", "<unicode>", 0, "contNormal", 0.02904888403011,
			 17.6055834534696, 0.221654036756853, 0.295821621993081, 0.258737829374967,
			 "contGamma:facExperimexperimental", "<unicode>", 0, "contNormal",
			 0.0189206500275651, 13.6748911373562, 0.336348042228162, 0.503786768211838,
			 0.42006740522, "facGenderm", "<unicode>", 0, "contGamma", 0.0427147456035957,
			 9.83424808655865))
})

test_that("Total effects table results match", {
	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_totalEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.619417420269258, -0.429267635860784, -0.524342528065021, "Total",
			 0, 0.0485084894182627, -10.8092940916774, -0.619417420269258,
			 -0.429267635860784, -0.524342528065021, "Total indirect", 0,
			 0.0485084894182627, -10.8092940916774))
})

test_that("Conceptual path plot matches", {
	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_conceptPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "conceptual-path-plot-factor-confounder_moderator")
})

test_that("Statistical path plot matches", {
	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_statPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "statistical-path-plot-factor-confounder_moderator")
})
