# This code is automatically generated by 'generate-tests.R'


test_that("Test that model number one_confounder - continuous works", {
 
options <- jaspTools::analysisOptions("ClassicProcess")
options$dependent <- "contNormal"
options$covariates <- list("contGamma", "contcor1", "contcor2", "debCollin1")
options$factors <- list("facGender", "facExperim")
options$statisticalPathPlotsCovariances <- TRUE
options$statisticalPathPlotsResidualVariances <- TRUE
options$errorCalculationMethod <- "standard"
options$naAction <- "fiml"
options$emulation <- "lavaan"
options$estimator <- "default"
options$moderationProbes <- list(list(probePercentile = 16, value = "16"), list(probePercentile = 50, 
    value = "50"), list(probePercentile = 84, value = "84"))
options$pathPlotsLegend <- TRUE
options$pathPlotsColorPalette <- "colorblind"
options$processModels <- list(list(conceptualPathPlot = TRUE, independentCovariances = TRUE, 
    inputType = "inputVariables", mediationEffects = TRUE, mediatorCovariances = TRUE, 
    modelNumber = 1, modelNumberCovariates = list(), modelNumberIndependent = "", 
    modelNumberMediators = list(), modelNumberModeratorW = "", 
    modelNumberModeratorZ = "", name = "Model 1", pathCoefficients = TRUE, 
    processRelationships = list(list(processDependent = "contNormal", 
        processIndependent = "contGamma", processType = "confounders", 
        processVariable = "contcor1")), residualCovariances = TRUE, 
    statisticalPathPlot = TRUE, totalEffects = TRUE, localTests = FALSE, 
    localTestType = "cis", localTestBootstrap = FALSE, localTestBootstrapSamples = 1000))
set.seed(1)
results <- jaspTools::runAnalysis("ClassicProcess", "debug", options)



	table <- results[["results"]][["modelSummaryTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(960.194063205136, 983.640594879029, 0, "Model 1", 100, -471.097031602568,
			 4))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_covariancesTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(0.732634590394826, 1.29452394334508, 1.01357926686995, "contcor1",
			 "<unicode>", 1.53743684450092e-12, "contcor1", 0.143341754588952,
			 7.07106781116569, 1.63922475925008, 2.89641756877381, 2.26782116401194,
			 "contGamma", "<unicode>", 1.53743684450092e-12, "contGamma",
			 0.320718344683959, 7.07106781262134, 0.779896467881489, 1.37803301156572,
			 1.0789647397236, "contNormal", "<unicode>", 1.53743684450092e-12,
			 "contNormal", 0.152588656833048, 7.07106781144378))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_mediationEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.0420059521826613, 0.367482204548676, 0.162738126183007, "contcor1",
			 "contNormal", "", "<unicode>", "", 0.11926845840203, 0.1044631840078,
			 1.55785148355095, -0.027115002941041, 0.0385272160356765, 0.00570610654731776,
			 "contcor1", "contGamma", "contNormal", "<unicode>", "<unicode>",
			 0.733292476299653, 0.0167457717321581, 0.34074909407489))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_pathCoefficientsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.159257084876543, 0.111124625427091, -0.0240662297247261, "contGamma",
			 "<unicode>", 0.72715964179294, "contNormal", 0.0689761935516088,
			 -0.348906318043188, -0.0420059521826613, 0.367482204548676,
			 0.162738126183007, "contcor1", "<unicode>", 0.11926845840203,
			 "contNormal", 0.1044631840078, 1.55785148355095, -0.530272916905354,
			 0.0560726277378983, -0.237100144583728, "contcor1", "<unicode>",
			 0.112943938943514, "contGamma", 0.149580693642401, -1.58509857662886
			))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_totalEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.0338982352403213, 0.370786700700972, 0.168444232730325, "Total",
			 0.102761008338914, 0.10323785006597, 1.63161314016795, -0.0420059521826613,
			 0.367482204548676, 0.162738126183007, "Total indirect", 0.11926845840203,
			 0.1044631840078, 1.55785148355095))



	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_conceptPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "conceptual-path-plot-continuous-one_confounder")



	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_statPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "statistical-path-plot-continuous-one_confounder")

})
test_that("Test that model number one_confounder - factor works", {
 
options <- jaspTools::analysisOptions("ClassicProcess")
options$dependent <- "contNormal"
options$covariates <- list("contGamma", "contcor1", "contcor2", "debCollin1")
options$factors <- list("facGender", "facExperim")
options$statisticalPathPlotsCovariances <- TRUE
options$statisticalPathPlotsResidualVariances <- TRUE
options$errorCalculationMethod <- "standard"
options$naAction <- "fiml"
options$emulation <- "lavaan"
options$estimator <- "default"
options$moderationProbes <- list(list(probePercentile = 16, value = "16"), list(probePercentile = 50, 
    value = "50"), list(probePercentile = 84, value = "84"))
options$pathPlotsLegend <- TRUE
options$pathPlotsColorPalette <- "colorblind"
options$processModels <- list(list(conceptualPathPlot = TRUE, independentCovariances = TRUE, 
    inputType = "inputVariables", mediationEffects = TRUE, mediatorCovariances = TRUE, 
    modelNumber = 1, modelNumberCovariates = list(), modelNumberIndependent = "", 
    modelNumberMediators = list(), modelNumberModeratorW = "", 
    modelNumberModeratorZ = "", name = "Model 1", pathCoefficients = TRUE, 
    processRelationships = list(list(processDependent = "contNormal", 
        processIndependent = "contGamma", processType = "confounders", 
        processVariable = "facExperim")), residualCovariances = TRUE, 
    statisticalPathPlot = TRUE, totalEffects = TRUE, localTests = FALSE, 
    localTestType = "cis", localTestBootstrap = FALSE, localTestBootstrapSamples = 1000))
set.seed(1)
results <- jaspTools::runAnalysis("ClassicProcess", "debug", options)



	table <- results[["results"]][["modelSummaryTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(824.37336567829, 847.819897352183, 0, "Model 1", 100, -403.186682839145,
			 4))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_covariancesTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(0.180704818055353, 0.319295223563333, 0.250000020809343, "facExperimexperimental",
			 "<unicode>", 1.53743684450092e-12, "facExperimexperimental",
			 0.0353553449454082, 7.07106722322652, 1.67091881606353, 2.95241917713298,
			 2.31166899659826, "contGamma", "<unicode>", 1.53743684450092e-12,
			 "contGamma", 0.326919364635719, 7.07106781262135, 0.797583248451353,
			 1.40928455391441, 1.10343390118288, "contNormal", "<unicode>",
			 1.53743684450092e-12, "contNormal", 0.156049118832815, 7.07106781144378
			))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_mediationEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.329844405685614, 0.496024877188678, 0.0830902357515322, "facExperimexperimental",
			 "contNormal", "", "<unicode>", "", 0.693299245993837, 0.210684810891589,
			 0.394381708865987, -0.0500653809891558, 0.0303840547660915,
			 -0.00984066311153218, "facExperimexperimental", "contGamma",
			 "contNormal", "<unicode>", "<unicode>", 0.63159016355888, 0.0205231923621613,
			 -0.479489883341709))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_pathCoefficientsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.178349084221068, 0.0924757112770427, -0.0429366864720126, "contGamma",
			 "<unicode>", 0.534292291302094, "contNormal", 0.0690892275660017,
			 -0.621467166223485, -0.329844405685614, 0.496024877188678, 0.0830902357515322,
			 "facExperimexperimental", "<unicode>", 0.693299245993837, "contNormal",
			 0.210684810891589, 0.394381708865987, -0.366802567861926, 0.825182751341926,
			 0.22919009174, "facExperimexperimental", "<unicode>", 0.451024688010575,
			 "contGamma", 0.304083475157217, 0.753707815334274))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_totalEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.339311551617825, 0.485810696897825, 0.07324957264, "Total",
			 0.727848824673947, 0.210494237400306, 0.347988493864076, -0.329844405685614,
			 0.496024877188678, 0.0830902357515322, "Total indirect", 0.693299245993837,
			 0.210684810891589, 0.394381708865987))



	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_conceptPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "conceptual-path-plot-factor-one_confounder")



	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_statPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "statistical-path-plot-factor-one_confounder")

})
test_that("Test that model number one_direct - continuous works", {
 
options <- jaspTools::analysisOptions("ClassicProcess")
options$dependent <- "contNormal"
options$covariates <- list("contGamma", "contcor1", "contcor2", "debCollin1")
options$factors <- list("facGender", "facExperim")
options$statisticalPathPlotsCovariances <- TRUE
options$statisticalPathPlotsResidualVariances <- TRUE
options$errorCalculationMethod <- "standard"
options$naAction <- "fiml"
options$emulation <- "lavaan"
options$estimator <- "default"
options$moderationProbes <- list(list(probePercentile = 16, value = "16"), list(probePercentile = 50, 
    value = "50"), list(probePercentile = 84, value = "84"))
options$pathPlotsLegend <- TRUE
options$pathPlotsColorPalette <- "colorblind"
options$processModels <- list(list(conceptualPathPlot = TRUE, independentCovariances = TRUE, 
    inputType = "inputVariables", mediationEffects = TRUE, mediatorCovariances = TRUE, 
    modelNumber = 1, modelNumberCovariates = list(), modelNumberIndependent = "", 
    modelNumberMediators = list(), modelNumberModeratorW = "", 
    modelNumberModeratorZ = "", name = "Model 1", pathCoefficients = TRUE, 
    processRelationships = list(list(processDependent = "contNormal", 
        processIndependent = "contGamma", processType = "directs", 
        processVariable = "")), residualCovariances = TRUE, statisticalPathPlot = TRUE, 
    totalEffects = TRUE, localTests = FALSE, localTestType = "cis", 
    localTestBootstrap = FALSE, localTestBootstrapSamples = 1000))
set.seed(1)
results <- jaspTools::runAnalysis("ClassicProcess", "debug", options)



	table <- results[["results"]][["modelSummaryTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(671.93697925528, 684.96283018522, 0, "Model 1", 100, -330.96848962764
			))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_covariancesTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(1.6804108956973, 2.96919114523388, 2.32480102046559, "contGamma",
			 "<unicode>", 1.53743684450092e-12, "contGamma", 0.328776513166141,
			 7.07106781466107, 0.798823784968434, 1.41147651187677, 1.1051501484226,
			 "contNormal", "<unicode>", 1.53743684450092e-12, "contNormal",
			 0.156291832845109, 7.07106781144378))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_mediationEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.176023203389167, 0.0942455484667592, -0.0408888274612038, "contGamma",
			 "contNormal", "<unicode>", 0.553151714317508, 0.0689473770915618,
			 -0.593043987835877))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_pathCoefficientsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.176023203389167, 0.0942455484667592, -0.0408888274612038, "contGamma",
			 "<unicode>", 0.553151714317508, "contNormal", 0.0689473770915618,
			 -0.593043987835877))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_totalEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.176023203389167, 0.0942455484667592, -0.0408888274612038, "Total",
			 0.553151714317508, 0.0689473770915618, -0.593043987835877))



	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_conceptPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "conceptual-path-plot-continuous-one_direct")



	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_statPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "statistical-path-plot-continuous-one_direct")

})
test_that("Test that model number one_direct - factor works", {
 
options <- jaspTools::analysisOptions("ClassicProcess")
options$dependent <- "contNormal"
options$covariates <- list("contGamma", "contcor1", "contcor2", "debCollin1")
options$factors <- list("facGender", "facExperim")
options$statisticalPathPlotsCovariances <- TRUE
options$statisticalPathPlotsResidualVariances <- TRUE
options$errorCalculationMethod <- "standard"
options$naAction <- "fiml"
options$emulation <- "lavaan"
options$estimator <- "default"
options$moderationProbes <- list(list(probePercentile = 16, value = "16"), list(probePercentile = 50, 
    value = "50"), list(probePercentile = 84, value = "84"))
options$pathPlotsLegend <- TRUE
options$pathPlotsColorPalette <- "colorblind"
options$processModels <- list(list(conceptualPathPlot = TRUE, independentCovariances = TRUE, 
    inputType = "inputVariables", mediationEffects = TRUE, mediatorCovariances = TRUE, 
    modelNumber = 1, modelNumberCovariates = list(), modelNumberIndependent = "", 
    modelNumberMediators = list(), modelNumberModeratorW = "", 
    modelNumberModeratorZ = "", name = "Model 1", pathCoefficients = TRUE, 
    processRelationships = list(list(processDependent = "contNormal", 
        processIndependent = "contGamma", processType = "directs", 
        processVariable = "")), residualCovariances = TRUE, statisticalPathPlot = TRUE, 
    totalEffects = TRUE, localTests = FALSE, localTestType = "cis", 
    localTestBootstrap = FALSE, localTestBootstrapSamples = 1000))
set.seed(1)
results <- jaspTools::runAnalysis("ClassicProcess", "debug", options)



	table <- results[["results"]][["modelSummaryTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(671.93697925528, 684.96283018522, 0, "Model 1", 100, -330.96848962764
			))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_covariancesTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(1.6804108956973, 2.96919114523388, 2.32480102046559, "contGamma",
			 "<unicode>", 1.53743684450092e-12, "contGamma", 0.328776513166141,
			 7.07106781466107, 0.798823784968434, 1.41147651187677, 1.1051501484226,
			 "contNormal", "<unicode>", 1.53743684450092e-12, "contNormal",
			 0.156291832845109, 7.07106781144378))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_mediationEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.176023203389167, 0.0942455484667592, -0.0408888274612038, "contGamma",
			 "contNormal", "<unicode>", 0.553151714317508, 0.0689473770915618,
			 -0.593043987835877))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_pathCoefficientsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.176023203389167, 0.0942455484667592, -0.0408888274612038, "contGamma",
			 "<unicode>", 0.553151714317508, "contNormal", 0.0689473770915618,
			 -0.593043987835877))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_totalEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.176023203389167, 0.0942455484667592, -0.0408888274612038, "Total",
			 0.553151714317508, 0.0689473770915618, -0.593043987835877))



	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_conceptPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "conceptual-path-plot-factor-one_direct")



	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_statPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "statistical-path-plot-factor-one_direct")

})
test_that("Test that model number two_confounder - continuous works", {
 
options <- jaspTools::analysisOptions("ClassicProcess")
options$dependent <- "contNormal"
options$covariates <- list("contGamma", "contcor1", "contcor2", "debCollin1")
options$factors <- list("facGender", "facExperim")
options$statisticalPathPlotsCovariances <- TRUE
options$statisticalPathPlotsResidualVariances <- TRUE
options$errorCalculationMethod <- "standard"
options$naAction <- "fiml"
options$emulation <- "lavaan"
options$estimator <- "default"
options$moderationProbes <- list(list(probePercentile = 16, value = "16"), list(probePercentile = 50, 
    value = "50"), list(probePercentile = 84, value = "84"))
options$pathPlotsLegend <- TRUE
options$pathPlotsColorPalette <- "colorblind"
options$processModels <- list(list(conceptualPathPlot = TRUE, independentCovariances = TRUE, 
    inputType = "inputVariables", mediationEffects = TRUE, mediatorCovariances = TRUE, 
    modelNumber = 1, modelNumberCovariates = list(), modelNumberIndependent = "", 
    modelNumberMediators = list(), modelNumberModeratorW = "", 
    modelNumberModeratorZ = "", name = "Model 1", pathCoefficients = TRUE, 
    processRelationships = list(list(processDependent = "contNormal", 
        processIndependent = "contGamma", processType = "confounders", 
        processVariable = "contcor1"), list(processDependent = "contNormal", 
        processIndependent = "contGamma", processType = "confounders", 
        processVariable = "contcor2")), residualCovariances = TRUE, 
    statisticalPathPlot = TRUE, totalEffects = TRUE, localTests = FALSE, 
    localTestType = "cis", localTestBootstrap = FALSE, localTestBootstrapSamples = 1000))
set.seed(1)
results <- jaspTools::runAnalysis("ClassicProcess", "debug", options)



	table <- results[["results"]][["modelSummaryTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(1196.12854848421, 1232.60093108804, 0, "Model 1", 100, -584.064274242105
			))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_covariancesTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(0.424979180919744, 0.896763104121614, 0.660871142520679, "contcor2",
			 "<unicode>", 3.99655943894572e-08, "contcor1", 0.120355253189151,
			 5.4910037161573, 0.732634592963226, 1.29452395230351, 1.01357927263337,
			 "contcor1", "<unicode>", 1.53743684450092e-12, "contcor1", 0.143341756219093,
			 7.07106777095817, 0.721541823114584, 1.27492365300028, 0.998232738057432,
			 "contcor2", "<unicode>", 1.53743684450092e-12, "contcor2", 0.141171428212636,
			 7.07106778401271, 1.63577445794209, 2.89032108123016, 2.26304776958613,
			 "contGamma", "<unicode>", 1.53743684450092e-12, "contGamma",
			 0.320043284770477, 7.07106781262135, 0.772432177868598, 1.36484403268291,
			 1.06863810527576, "contNormal", "<unicode>", 1.53743684450092e-12,
			 "contNormal", 0.151128250183979, 7.07106781144378))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_mediationEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.0183967830162192, 0.521461905534409, 0.251532561259095, "contcor1",
			 "contNormal", "", "<unicode>", "", 0.067792370251071, 0.137721583868113,
			 1.8263844649069, -0.0345845435803312, 0.0470351073738792, 0.00622528189677404,
			 "contcor1", "contGamma", "contNormal", "<unicode>", "<unicode>",
			 0.7649551805981, 0.0208217221331657, 0.298980163934575))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_pathCoefficientsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.155651256626207, 0.113717085937514, -0.0209670853443464, "contGamma",
			 "<unicode>", 0.760275337196381, "contNormal", 0.0687176766227503,
			 -0.305119241144496, -0.0183967830162192, 0.521461905534409,
			 0.251532561259095, "contcor1", "<unicode>", 0.067792370251071,
			 "contNormal", 0.137721583868113, 1.8263844649069, -0.404335782858585,
			 0.134221360435661, -0.135057211211462, "contcor2", "<unicode>",
			 0.325595679387153, "contNormal", 0.137389550915812, -0.983023893092285,
			 -0.685382138339048, 0.0915674240346943, -0.296907357152177,
			 "contcor1", "<unicode>", 0.134138263509527, "contGamma", 0.198205061037402,
			 -1.49798070542785, -0.299723108402101, 0.483175970242395, 0.091726430920147,
			 "contcor2", "<unicode>", 0.646041258390023, "contGamma", 0.199722822669167,
			 0.45926864889191))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_totalEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.00931723446549082, 0.524832920777229, 0.257757843155869, "Total",
			 0.0585458573430464, 0.136265298611614, 1.89158828977093, -0.0183967830162192,
			 0.521461905534409, 0.251532561259095, "Total indirect", 0.067792370251071,
			 0.137721583868113, 1.8263844649069))



	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_conceptPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "conceptual-path-plot-continuous-two_confounder")



	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_statPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "statistical-path-plot-continuous-two_confounder")

})
test_that("Test that model number two_confounder - factor works", {
 
options <- jaspTools::analysisOptions("ClassicProcess")
options$dependent <- "contNormal"
options$covariates <- list("contGamma", "contcor1", "contcor2", "debCollin1")
options$factors <- list("facGender", "facExperim")
options$statisticalPathPlotsCovariances <- TRUE
options$statisticalPathPlotsResidualVariances <- TRUE
options$errorCalculationMethod <- "standard"
options$naAction <- "fiml"
options$emulation <- "lavaan"
options$estimator <- "default"
options$moderationProbes <- list(list(probePercentile = 16, value = "16"), list(probePercentile = 50, 
    value = "50"), list(probePercentile = 84, value = "84"))
options$pathPlotsLegend <- TRUE
options$pathPlotsColorPalette <- "colorblind"
options$processModels <- list(list(conceptualPathPlot = TRUE, independentCovariances = TRUE, 
    inputType = "inputVariables", mediationEffects = TRUE, mediatorCovariances = TRUE, 
    modelNumber = 1, modelNumberCovariates = list(), modelNumberIndependent = "", 
    modelNumberMediators = list(), modelNumberModeratorW = "", 
    modelNumberModeratorZ = "", name = "Model 1", pathCoefficients = TRUE, 
    processRelationships = list(list(processDependent = "contNormal", 
        processIndependent = "contGamma", processType = "confounders", 
        processVariable = "facExperim"), list(processDependent = "contNormal", 
        processIndependent = "contGamma", processType = "confounders", 
        processVariable = "facGender")), residualCovariances = TRUE, 
    statisticalPathPlot = TRUE, totalEffects = TRUE, localTests = FALSE, 
    localTestType = "cis", localTestBootstrap = FALSE, localTestBootstrapSamples = 1000))
set.seed(1)
results <- jaspTools::runAnalysis("ClassicProcess", "debug", options)



	table <- results[["results"]][["modelSummaryTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(969.933634417418, 1006.40601702125, 0, "Model 1", 100, -470.966817208709
			))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_covariancesTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.00962232469041584, 0.0896223218018369, 0.0399999985557105,
			 "facGenderm", "<unicode>", 0.114128624284983, "facExperimexperimental",
			 0.0253179770840388, 1.57990499884478, 0.180704807310708, 0.319295186083387,
			 0.249999996697048, "facExperimexperimental", "<unicode>", 1.53743684450092e-12,
			 "facExperimexperimental", 0.0353553381250528, 7.07106790529879,
			 0.180704807218812, 0.319295185762859, 0.249999996490836, "facGenderm",
			 "<unicode>", 1.53743684450092e-12, "facGenderm", 0.0353553380667272,
			 7.07106791113135, 1.6436585661041, 2.90425185507047, 2.27395521058729,
			 "contGamma", "<unicode>", 1.53743684450092e-12, "contGamma",
			 0.321585829869774, 7.07106781262135, 0.755960143301373, 1.33573887791417,
			 1.04584951060777, "contNormal", "<unicode>", 1.53743684450092e-12,
			 "contNormal", 0.147905456219098, 7.07106781144378))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_mediationEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.397396510584462, 0.416025502052742, 0.0093144957341401, "facExperimexperimental",
			 "contNormal", "", "<unicode>", "", 0.964197302009531, 0.207509428503119,
			 0.0448870964627041, -0.0543727189027194, 0.0333398342079703,
			 -0.0105164423473746, "facExperimexperimental", "contGamma",
			 "contNormal", "<unicode>", "<unicode>", 0.63836482029219, 0.0223760624691461,
			 -0.469986279394574))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_pathCoefficientsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.196182963799885, 0.0696578956403529, -0.0632625340797659, "contGamma",
			 "<unicode>", 0.350907267674392, "contNormal", 0.0678177919434123,
			 -0.932830932221335, -0.397396510584462, 0.416025502052742, 0.0093144957341401,
			 "facExperimexperimental", "<unicode>", 0.964197302009531, "contNormal",
			 0.207509428503119, 0.0448870964627041, 0.0807497114696924, 0.899678077647834,
			 0.490213894558763, "facGenderm", "<unicode>", 0.0189514272255094,
			 "contNormal", 0.208914136340704, 2.34648503516921, -0.43259073960758,
			 0.765060581366201, 0.16623492087931, "facExperimexperimental",
			 "<unicode>", 0.586380226077632, "contGamma", 0.305528910332206,
			 0.544089005189594, -0.205355842611306, 0.992295478369927, 0.39346981787931,
			 "facGenderm", "<unicode>", 0.197804552739381, "contGamma", 0.305528910334107,
			 1.28783170616829))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_totalEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.409075392315575, 0.406671499089106, -0.00120194661323445, "Total",
			 0.995391649700707, 0.208102520719562, -0.005775742692008, -0.397396510584462,
			 0.416025502052742, 0.0093144957341401, "Total indirect", 0.964197302009531,
			 0.207509428503119, 0.0448870964627041))



	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_conceptPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "conceptual-path-plot-factor-two_confounder")



	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_statPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "statistical-path-plot-factor-two_confounder")

})
test_that("Test that model number confounder_X_Y - continuous works", {
 
options <- jaspTools::analysisOptions("ClassicProcess")
options$dependent <- "contNormal"
options$covariates <- list("contGamma", "contcor1", "contcor2", "debCollin1")
options$factors <- list("facGender", "facExperim")
options$statisticalPathPlotsCovariances <- TRUE
options$statisticalPathPlotsResidualVariances <- TRUE
options$errorCalculationMethod <- "standard"
options$naAction <- "fiml"
options$emulation <- "lavaan"
options$estimator <- "default"
options$moderationProbes <- list(list(probePercentile = 16, value = "16"), list(probePercentile = 50, 
    value = "50"), list(probePercentile = 84, value = "84"))
options$pathPlotsLegend <- TRUE
options$pathPlotsColorPalette <- "colorblind"
options$processModels <- list(list(conceptualPathPlot = TRUE, independentCovariances = TRUE, 
    inputType = "inputVariables", mediationEffects = TRUE, mediatorCovariances = TRUE, 
    modelNumber = 1, modelNumberCovariates = list(), modelNumberIndependent = "", 
    modelNumberMediators = list(), modelNumberModeratorW = "", 
    modelNumberModeratorZ = "", name = "Model 1", pathCoefficients = TRUE, 
    processRelationships = list(list(processDependent = "contNormal", 
        processIndependent = "contGamma", processType = "mediators", 
        processVariable = "debCollin1"), list(processDependent = "contNormal", 
        processIndependent = "contGamma", processType = "confounders", 
        processVariable = "contcor2")), residualCovariances = TRUE, 
    statisticalPathPlot = TRUE, totalEffects = TRUE, localTests = FALSE, 
    localTestType = "cis", localTestBootstrap = FALSE, localTestBootstrapSamples = 1000))
set.seed(1)
results <- jaspTools::runAnalysis("ClassicProcess", "debug", options)



	table <- results[["results"]][["modelSummaryTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(752.56251014022, 789.034892744054, 0, "Model 1", 100, -362.28125507011
			))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_covariancesTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(0.721541820201591, 1.27492364283993, 0.998232731520759, "contcor2",
			 "<unicode>", 1.53743684450092e-12, "contcor2", 0.141171426363785,
			 7.0710678303158, -0.337100829871576, 0.496772437940447, 0.0798358040344355,
			 "contGamma", "<unicode>", 0.707439182019051, "debCollin1", 0.212726681303715,
			 0.37529755809264, 1.67248036473138, 2.95517835937815, 2.31382936205476,
			 "contGamma", "<unicode>", 1.53743684450092e-12, "contGamma",
			 0.327224889019525, 7.07106775706385, -0.0195801668451294, 0.0380140593879026,
			 0.00921694627138661, "debCollin1", "<unicode>", 0.530452278404126,
			 "debCollin1", 0.0146926746326279, 0.627315754404483, 0.797840916252579,
			 1.40973983837224, 1.10379037731241, "contNormal", "<unicode>",
			 1.53743684450092e-12, "contNormal", 0.15609953217157, 7.07106781139628
			))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_mediationEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.176275917662267, 0.23731320938853, 0.0305186458631314, "contcor2",
			 "contNormal", "", "", "<unicode>", "", "", 0.772389630553604,
			 0.105509369129519, 0.289250576654175, -0.0146865234869237, 0.0235011295591785,
			 0.00440730303612741, "contcor2", "contGamma", "contNormal",
			 "", "<unicode>", "<unicode>", "", 0.650976769103064, 0.00974192723624556,
			 0.452405661554288, -0.0137432740209935, 0.0112230747572484,
			 -0.00126009963187255, "contcor2", "contGamma", "debCollin1",
			 "contNormal", "<unicode>", "<unicode>", "<unicode>", 0.843165318039053,
			 0.0063690835584667, -0.197846302424066))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_pathCoefficientsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.179344122869922, 0.0952661458587369, -0.0420389885055924, "contGamma",
			 "<unicode>", 0.548448851692891, "contNormal", 0.0700549272575286,
			 -0.600086106021538, -2.83802376966792, 2.28501281096033, -0.276505479353799,
			 "debCollin1", "<unicode>", 0.832442407469691, "contNormal",
			 1.3069211018769, -0.211570139128294, -0.176275917662267, 0.23731320938853,
			 0.0305186458631314, "contcor2", "<unicode>", 0.772389630553604,
			 "contNormal", 0.105509369129519, 0.289250576654175, -0.223110070724047,
			 0.13617190282424, -0.0434690839499035, "contGamma", "<unicode>",
			 0.635309333785758, "debCollin1", 0.0916552488673916, -0.47426726223607,
			 -0.403237897246725, 0.193560966721096, -0.104838465262814, "contcor2",
			 "<unicode>", 0.491071293096679, "contGamma", 0.152247405736864,
			 -0.688605922415593))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_totalEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.172816800526246, 0.240148499061018, 0.0336658492673863, "Total",
			 0.749300959047747, 0.105350226546172, 0.319561242259233, -0.17738968874516,
			 0.235906781207678, 0.0292585462312589, "Total indirect", 0.78139319035638,
			 0.105434710334697, 0.277503927675992))



	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_conceptPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "conceptual-path-plot-continuous-confounder_X_Y")



	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_statPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "statistical-path-plot-continuous-confounder_X_Y")

})
test_that("Test that model number confounder_X_Y - factor works", {
 
options <- jaspTools::analysisOptions("ClassicProcess")
options$dependent <- "contNormal"
options$covariates <- list("contGamma", "contcor1", "contcor2", "debCollin1")
options$factors <- list("facGender", "facExperim")
options$statisticalPathPlotsCovariances <- TRUE
options$statisticalPathPlotsResidualVariances <- TRUE
options$errorCalculationMethod <- "standard"
options$naAction <- "fiml"
options$emulation <- "lavaan"
options$estimator <- "default"
options$moderationProbes <- list(list(probePercentile = 16, value = "16"), list(probePercentile = 50, 
    value = "50"), list(probePercentile = 84, value = "84"))
options$pathPlotsLegend <- TRUE
options$pathPlotsColorPalette <- "colorblind"
options$processModels <- list(list(conceptualPathPlot = TRUE, independentCovariances = TRUE, 
    inputType = "inputVariables", mediationEffects = TRUE, mediatorCovariances = TRUE, 
    modelNumber = 1, modelNumberCovariates = list(), modelNumberIndependent = "", 
    modelNumberMediators = list(), modelNumberModeratorW = "", 
    modelNumberModeratorZ = "", name = "Model 1", pathCoefficients = TRUE, 
    processRelationships = list(list(processDependent = "contNormal", 
        processIndependent = "contGamma", processType = "mediators", 
        processVariable = "debCollin1"), list(processDependent = "contNormal", 
        processIndependent = "contGamma", processType = "confounders", 
        processVariable = "facGender")), residualCovariances = TRUE, 
    statisticalPathPlot = TRUE, totalEffects = TRUE, localTests = FALSE, 
    localTestType = "cis", localTestBootstrap = FALSE, localTestBootstrapSamples = 1000))
set.seed(1)
results <- jaspTools::runAnalysis("ClassicProcess", "debug", options)



	table <- results[["results"]][["modelSummaryTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(607.365516379342, 643.837898983176, 0, "Model 1", 100, -289.682758189671
			))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_covariancesTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(0.180704809305648, 0.319295193044861, 0.250000001175255, "facGenderm",
			 "<unicode>", 1.53743684450092e-12, "facGenderm", 0.035355339392049,
			 7.07106777856237, -0.149942240046712, 0.204469726295866, 0.0272637431245771,
			 "contGamma", "<unicode>", 0.762997321314972, "debCollin1", 0.0904128772615553,
			 0.301547124152523, 1.6485243332325, 2.91284938716785, 2.28068686020018,
			 "contGamma", "<unicode>", 1.53743684450092e-12, "contGamma",
			 0.322537828222402, 7.07106782720555, 0.00219716761973208, 0.0113929176945557,
			 0.0067950426571439, "debCollin1", "<unicode>", 0.00377273792243105,
			 "debCollin1", 0.00234589771734546, 2.89656390681557, 0.755846181346825,
			 1.33553751357751, 1.04569184746217, "contNormal", "<unicode>",
			 1.53743684450092e-12, "contNormal", 0.147883159283338, 7.07106781143798
			))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_mediationEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(0.0859003151554296, 0.895699802278834, 0.490800058717132, "facGenderm",
			 "contNormal", "", "", "<unicode>", "", "", 0.0175121668886125,
			 0.206585297870522, 2.37577438363858, -0.0953627168761149, 0.0411095548346247,
			 -0.0271265810207451, "facGenderm", "contGamma", "contNormal",
			 "", "<unicode>", "<unicode>", "", 0.435883275295673, 0.0348149947619486,
			 -0.779163725464449, -0.0210117568450086, 0.0239241658212091,
			 0.00145620448810027, "facGenderm", "contGamma", "debCollin1",
			 "contNormal", "<unicode>", "<unicode>", "<unicode>", 0.898916540794359,
			 0.0114634562218149, 0.127030143433454))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_pathCoefficientsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.199131680292892, 0.0699782265211687, -0.0645767268858618, "contGamma",
			 "<unicode>", 0.346888280600299, "contNormal", 0.0686517479241368,
			 -0.940642137141533, -2.65809965637266, 2.32566023378808, -0.166219711292289,
			 "debCollin1", "<unicode>", 0.895982174661907, "contNormal",
			 1.27139068102067, -0.130738500583351, 0.0859003151554296, 0.895699802278834,
			 0.490800058717132, "facGenderm", "<unicode>", 0.0175121668886125,
			 "contNormal", 0.206585297870522, 2.37577438363858, -0.0977783152950906,
			 0.0560672956625108, -0.0208555098162899, "contGamma", "<unicode>",
			 0.595148202837987, "debCollin1", 0.0392470504996816, -0.531390500706775,
			 -0.171917837733418, 1.01205273861469, 0.420067450440634, "facGenderm",
			 "<unicode>", 0.164294314653492, "contGamma", 0.302038860327821,
			 1.39077286275253))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_totalEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(0.0625107971036305, 0.867748567265343, 0.465129682184487, "Total",
			 0.0235575803680084, 0.205421573180254, 2.264268912868, 0.0874078079953342,
			 0.89710471841513, 0.492256263205232, "Total indirect", 0.0171663559416233,
			 0.206559129863248, 2.3831251783987))



	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_conceptPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "conceptual-path-plot-factor-confounder_X_Y")



	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_statPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "statistical-path-plot-factor-confounder_X_Y")

})
test_that("Test that model number confounder_X_M - continuous works", {
 
options <- jaspTools::analysisOptions("ClassicProcess")
options$dependent <- "contNormal"
options$covariates <- list("contGamma", "contcor1", "contcor2", "debCollin1")
options$factors <- list("facGender", "facExperim")
options$statisticalPathPlotsCovariances <- TRUE
options$statisticalPathPlotsResidualVariances <- TRUE
options$errorCalculationMethod <- "standard"
options$naAction <- "fiml"
options$emulation <- "lavaan"
options$estimator <- "default"
options$moderationProbes <- list(list(probePercentile = 16, value = "16"), list(probePercentile = 50, 
    value = "50"), list(probePercentile = 84, value = "84"))
options$pathPlotsLegend <- TRUE
options$pathPlotsColorPalette <- "colorblind"
options$processModels <- list(list(conceptualPathPlot = TRUE, independentCovariances = TRUE, 
    inputType = "inputVariables", mediationEffects = TRUE, mediatorCovariances = TRUE, 
    modelNumber = 1, modelNumberCovariates = list(), modelNumberIndependent = "", 
    modelNumberMediators = list(), modelNumberModeratorW = "", 
    modelNumberModeratorZ = "", name = "Model 1", pathCoefficients = TRUE, 
    processRelationships = list(list(processDependent = "contNormal", 
        processIndependent = "contGamma", processType = "mediators", 
        processVariable = "debCollin1"), list(processDependent = "debCollin1", 
        processIndependent = "contGamma", processType = "confounders", 
        processVariable = "contcor2")), residualCovariances = TRUE, 
    statisticalPathPlot = TRUE, totalEffects = TRUE, localTests = FALSE, 
    localTestType = "cis", localTestBootstrap = FALSE, localTestBootstrapSamples = 1000))
set.seed(1)
results <- jaspTools::runAnalysis("ClassicProcess", "debug", options)



	table <- results[["results"]][["modelSummaryTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(752.646141055907, 789.118523659741, 0, "Model 1", 100, -362.323070527954
			))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_covariancesTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(0.721541835093301, 1.27492369478134, 0.998232764937321, "contcor2",
			 "<unicode>", 1.53743684450092e-12, "contcor2", 0.141171435815415,
			 7.07106759360681, -607.579077577274, 607.579077577617, 1.71337620216989e-10,
			 "contGamma", "<unicode>", 0.999999999999559, "debCollin1", 309.995021525881,
			 5.5271087701221e-13, 1.67248030464117, 2.95517838310886, 2.31382934387501,
			 "contGamma", "<unicode>", 1.53743684450092e-12, "contGamma",
			 0.327224910402804, 7.07106723943101, 0.00467108277854578, 0.00825353945337524,
			 0.00646231111596051, "debCollin1", "<unicode>", 1.53743684450092e-12,
			 "debCollin1", 0.000913908802173771, 7.07106781397622, 0.798508437001226,
			 1.41091930982897, 1.1047138734151, "contNormal", "<unicode>",
			 1.53743684450092e-12, "contNormal", 0.156230134241844, 7.07106781144413
			))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_mediationEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.0147847276564638, 0.0238549732569569, 0.00453512280024657,
			 "contcor2", "contGamma", "contNormal", "", "<unicode>", "<unicode>",
			 "", 0.645458778461175, 0.00985724768878554, 0.460080028769706,
			 -7.14659929533556, 7.14472142012911, -0.000938937603223406,
			 "contcor2", "debCollin1", "contNormal", "", "<unicode>", "<unicode>",
			 "", 0.999794513871296, 3.64581207312808, -0.000257538672973291,
			 -7.14589764683217, 7.14540970657504, -0.000243970128566898,
			 "contcor2", "contGamma", "debCollin1", "contNormal", "<unicode>",
			 "<unicode>", "<unicode>", 0.99994660718193, 3.64580866437731,
			 -6.69179737682606e-05))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_pathCoefficientsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.180371895864293, 0.0938554961562729, -0.0432581998540102, "contGamma",
			 "<unicode>", 0.536343400510011, "contNormal", 0.0699572528331227,
			 -0.618351894937886, -2.81958314195831, 2.3004487096865, -0.259567216135904,
			 "debCollin1", "<unicode>", 0.842476879751126, "contNormal",
			 1.30615457529602, -0.198726261841618, -262.594916041887, 262.576985384885,
			 -0.00896532850087182, "contGamma", "<unicode>", 0.999946607178255,
			 "debCollin1", 133.974885653323, -6.69179783744747e-05, -27.5254923407673,
			 27.5327269801582, 0.00361731969545721, "contcor2", "<unicode>",
			 0.999794513698742, "debCollin1", 14.0457222059226, 0.000257538889237886,
			 -0.403237789098099, 0.193560880879453, -0.104838454109323, "contcor2",
			 "<unicode>", 0.491071198315604, "contGamma", 0.152247356248641,
			 -0.688606072988926))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_totalEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.0178966075516063, 0.0246010376885188, 0.00335221506845627,
			 "Total", 0.757166356594585, 0.0108414352445609, 0.309203993091049,
			 -0.0135662296914656, 0.011200414227885, -0.0011829077317903,
			 "Total indirect", 0.851484914508891, 0.0063181375052569, -0.187224119577342
			))



	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_conceptPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "conceptual-path-plot-continuous-confounder_X_M")



	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_statPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "statistical-path-plot-continuous-confounder_X_M")

})
test_that("Test that model number confounder_X_M - factor works", {
 
options <- jaspTools::analysisOptions("ClassicProcess")
options$dependent <- "contNormal"
options$covariates <- list("contGamma", "contcor1", "contcor2", "debCollin1")
options$factors <- list("facGender", "facExperim")
options$statisticalPathPlotsCovariances <- TRUE
options$statisticalPathPlotsResidualVariances <- TRUE
options$errorCalculationMethod <- "standard"
options$naAction <- "fiml"
options$emulation <- "lavaan"
options$estimator <- "default"
options$moderationProbes <- list(list(probePercentile = 16, value = "16"), list(probePercentile = 50, 
    value = "50"), list(probePercentile = 84, value = "84"))
options$pathPlotsLegend <- TRUE
options$pathPlotsColorPalette <- "colorblind"
options$processModels <- list(list(conceptualPathPlot = TRUE, independentCovariances = TRUE, 
    inputType = "inputVariables", mediationEffects = TRUE, mediatorCovariances = TRUE, 
    modelNumber = 1, modelNumberCovariates = list(), modelNumberIndependent = "", 
    modelNumberMediators = list(), modelNumberModeratorW = "", 
    modelNumberModeratorZ = "", name = "Model 1", pathCoefficients = TRUE, 
    processRelationships = list(list(processDependent = "contNormal", 
        processIndependent = "contGamma", processType = "mediators", 
        processVariable = "debCollin1"), list(processDependent = "debCollin1", 
        processIndependent = "contGamma", processType = "confounders", 
        processVariable = "facGender")), residualCovariances = TRUE, 
    statisticalPathPlot = TRUE, totalEffects = TRUE, localTests = FALSE, 
    localTestType = "cis", localTestBootstrap = FALSE, localTestBootstrapSamples = 1000))
set.seed(1)
results <- jaspTools::runAnalysis("ClassicProcess", "debug", options)



	table <- results[["results"]][["modelSummaryTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(612.856280580506, 649.32866318434, 0, "Model 1", 100, -292.428140290253
			))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_covariancesTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(0.180704815524767, 0.319295214736841, 0.250000015130804, "facGenderm",
			 "<unicode>", 1.53743684450092e-12, "facGenderm", 0.0353553433392801,
			 7.07106738383875, 1.64852537738581, 2.91284834539771, 2.28068686139176,
			 "contGamma", "<unicode>", 1.53743684450092e-12, "contGamma",
			 0.322537296089295, 7.07107949699046, 0.00467636180430558, 0.00826189220852088,
			 0.00646912700641323, "debCollin1", "<unicode>", 1.52211576676109e-12,
			 "debCollin1", 0.00091469293122157, 7.07245763643732, 0.798508437001174,
			 1.41091930982902, 1.1047138734151, "contNormal", "<unicode>",
			 1.53743684450092e-12, "contNormal", 0.15623013424187, 7.07106781144295
			))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_mediationEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.0812046417471832, 0.0448619220894113, -0.018171359828886, "facGenderm",
			 "contGamma", "contNormal", "", "<unicode>", "<unicode>", "",
			 0.572058586763452, 0.0321604286688407, -0.565022314099054, "",
			 "", 0.00130342699162342, "facGenderm", "debCollin1", "contNormal",
			 "", "<unicode>", "<unicode>", "", "", "", "", "", "", 0.000970569137243933,
			 "facGenderm", "contGamma", "debCollin1", "contNormal", "<unicode>",
			 "<unicode>", "<unicode>", "", "", ""))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_pathCoefficientsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.180371895864541, 0.0938554961564221, -0.0432581998540597, "contGamma",
			 "<unicode>", 0.536343400510135, "contNormal", 0.0699572528332241,
			 -0.618351894937698, -2.81958314197502, 2.30044870970319, -0.259567216135916,
			 "debCollin1", "<unicode>", 0.842476879752134, "contNormal",
			 1.30615457530454, -0.19872626184033, "", "", -0.00890138637112046,
			 "contGamma", "<unicode>", "", "debCollin1", "", "", "", "",
			 -0.00502153935703851, "facGenderm", "<unicode>", "", "debCollin1",
			 "", "", -0.171917884556499, 1.01205269784927, 0.420067406646386,
			 "facGenderm", "<unicode>", 0.164294360794206, "contGamma", 0.302038861873172,
			 1.39077271064137))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_totalEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.079416444198823, 0.0476217167987858, -0.0158973637000186, "Total",
			 0.623756169473329, 0.0324082896419704, -0.490533868823201, -0.0216391957105213,
			 0.0261871879682561, 0.00227399612886735, "Total indirect", 0.852146453356244,
			 0.0122008322744769, 0.18638041059087))



	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_conceptPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "conceptual-path-plot-factor-confounder_X_M")



	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_statPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "statistical-path-plot-factor-confounder_X_M")

})
test_that("Test that model number confounder_M_Y - continuous works", {
 
options <- jaspTools::analysisOptions("ClassicProcess")
options$dependent <- "contNormal"
options$covariates <- list("contGamma", "contcor1", "contcor2", "debCollin1")
options$factors <- list("facGender", "facExperim")
options$statisticalPathPlotsCovariances <- TRUE
options$statisticalPathPlotsResidualVariances <- TRUE
options$errorCalculationMethod <- "standard"
options$naAction <- "fiml"
options$emulation <- "lavaan"
options$estimator <- "default"
options$moderationProbes <- list(list(probePercentile = 16, value = "16"), list(probePercentile = 50, 
    value = "50"), list(probePercentile = 84, value = "84"))
options$pathPlotsLegend <- TRUE
options$pathPlotsColorPalette <- "colorblind"
options$processModels <- list(list(conceptualPathPlot = TRUE, independentCovariances = TRUE, 
    inputType = "inputVariables", mediationEffects = TRUE, mediatorCovariances = TRUE, 
    modelNumber = 1, modelNumberCovariates = list(), modelNumberIndependent = "", 
    modelNumberMediators = list(), modelNumberModeratorW = "", 
    modelNumberModeratorZ = "", name = "Model 1", pathCoefficients = TRUE, 
    processRelationships = list(list(processDependent = "contNormal", 
        processIndependent = "contGamma", processType = "mediators", 
        processVariable = "debCollin1"), list(processDependent = "contNormal", 
        processIndependent = "debCollin1", processType = "confounders", 
        processVariable = "contcor2")), residualCovariances = TRUE, 
    statisticalPathPlot = TRUE, totalEffects = TRUE, localTests = FALSE, 
    localTestType = "cis", localTestBootstrap = FALSE, localTestBootstrapSamples = 1000))
set.seed(1)
results <- jaspTools::runAnalysis("ClassicProcess", "debug", options)



	table <- results[["results"]][["modelSummaryTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(752.562510140221, 789.034892744054, 0, "Model 1", 100, -362.28125507011
			))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_covariancesTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.40393421658602, 0.19462797334002, -0.104653121623, "contcor2",
			 "<unicode>", 0.493114548399417, "contGamma", 0.152697242053278,
			 -0.6853635351612, 1.68041089751753, 2.96919115158277, 2.32480102455015,
			 "contGamma", "<unicode>", 1.53743684450092e-12, "contGamma",
			 0.32877651432143, 7.07106780223754, 0.721541823493171, 1.27492365432077,
			 0.998232738906971, "contcor2", "<unicode>", 1.53743684450092e-12,
			 "contcor2", 0.141171428452922, 7.07106777799491, 0.00467108280296489,
			 0.00825353952843831, 0.0064623111657016, "debCollin1", "<unicode>",
			 1.53743684450092e-12, "debCollin1", 0.000913908815093384, 7.07106776844173,
			 0.797840916249277, 1.40973983836072, 1.103790377305, "contNormal",
			 "<unicode>", 1.53743684450092e-12, "contNormal", 0.156099532169474,
			 7.07106781144376))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_mediationEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.179344124972709, 0.0952661437540926, -0.0420389906093081, "contGamma",
			 "contNormal", "", "<unicode>", "", 0.548448831678073, 0.0700549272570547,
			 -0.600086136055114, -0.0206637960251635, 0.0256217211336616,
			 0.00247896255424904, "contGamma", "debCollin1", "contNormal",
			 "<unicode>", "<unicode>", 0.833711582120974, 0.0118077468575748,
			 0.20994374152413))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_pathCoefficientsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.179344124972709, 0.0952661437540926, -0.0420389906093081, "contGamma",
			 "<unicode>", 0.548448831678073, "contNormal", 0.0700549272570547,
			 -0.600086136055114, -2.83802377006717, 2.28501281042778, -0.276505479819698,
			 "debCollin1", "<unicode>", 0.832442407187256, "contNormal",
			 1.30692110184289, -0.211570139490285, -0.176275917685606, 0.237313209364911,
			 0.0305186458396525, "contcor2", "<unicode>", 0.772389630723732,
			 "contNormal", 0.105509369129447, 0.289250576431842, -0.0193233396980085,
			 0.00139268200641049, -0.00896532884579901, "contGamma", "<unicode>",
			 0.0898029910226996, "debCollin1", 0.00528479652376889, -1.69643784873771,
			 -0.0121898224606108, 0.0194244613404918, 0.00361731943994051,
			 "contcor2", "<unicode>", 0.653778113481815, "debCollin1", 0.00806501651317884,
			 0.448519780961333))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_totalEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.174961351145321, 0.0958412950352028, -0.039560028055059, "Total",
			 0.566888387519272, 0.0690835771260545, -0.572640122309752, -0.0206637960251635,
			 0.0256217211336616, 0.00247896255424904, "Total indirect", 0.833711582120974,
			 0.0118077468575748, 0.20994374152413))



	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_conceptPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "conceptual-path-plot-continuous-confounder_M_Y")



	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_statPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "statistical-path-plot-continuous-confounder_M_Y")

})
test_that("Test that model number confounder_M_Y - factor works", {
 
options <- jaspTools::analysisOptions("ClassicProcess")
options$dependent <- "contNormal"
options$covariates <- list("contGamma", "contcor1", "contcor2", "debCollin1")
options$factors <- list("facGender", "facExperim")
options$statisticalPathPlotsCovariances <- TRUE
options$statisticalPathPlotsResidualVariances <- TRUE
options$errorCalculationMethod <- "standard"
options$naAction <- "fiml"
options$emulation <- "lavaan"
options$estimator <- "default"
options$moderationProbes <- list(list(probePercentile = 16, value = "16"), list(probePercentile = 50, 
    value = "50"), list(probePercentile = 84, value = "84"))
options$pathPlotsLegend <- TRUE
options$pathPlotsColorPalette <- "colorblind"
options$processModels <- list(list(conceptualPathPlot = TRUE, independentCovariances = TRUE, 
    inputType = "inputVariables", mediationEffects = TRUE, mediatorCovariances = TRUE, 
    modelNumber = 1, modelNumberCovariates = list(), modelNumberIndependent = "", 
    modelNumberMediators = list(), modelNumberModeratorW = "", 
    modelNumberModeratorZ = "", name = "Model 1", pathCoefficients = TRUE, 
    processRelationships = list(list(processDependent = "contNormal", 
        processIndependent = "contGamma", processType = "mediators", 
        processVariable = "debCollin1"), list(processDependent = "contNormal", 
        processIndependent = "debCollin1", processType = "confounders", 
        processVariable = "facGender")), residualCovariances = TRUE, 
    statisticalPathPlot = TRUE, totalEffects = TRUE, localTests = FALSE, 
    localTestType = "cis", localTestBootstrap = FALSE, localTestBootstrapSamples = 1000))
set.seed(1)
results <- jaspTools::runAnalysis("ClassicProcess", "debug", options)



	table <- results[["results"]][["modelSummaryTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(607.365516379343, 643.837898983176, 0, "Model 1", 100, -289.682758189671
			))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_covariancesTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.0458149245495941, 0.255848631149535, 0.105016853299971, "facGenderm",
			 "<unicode>", 0.172370035376217, "contGamma", 0.0769564027907179,
			 1.36462788659136, 1.68041089310599, 2.96919113619555, 2.32480101465077,
			 "contGamma", "<unicode>", 1.53743684450092e-12, "contGamma",
			 0.328776511521461, 7.07106783234731, 0.180704808888483, 0.319295191589812,
			 0.250000000239148, "facGenderm", "<unicode>", 1.53743684450092e-12,
			 "facGenderm", 0.0353553391272779, 7.07106780503948, 0.0046760093957327,
			 0.00826224449975787, 0.00646912694774529, "debCollin1", "<unicode>",
			 1.53743684450092e-12, "debCollin1", 0.000914872704884614, 7.07106782528963,
			 0.755846181346482, 1.33553751357631, 1.0456918474614, "contNormal",
			 "<unicode>", 1.53743684450092e-12, "contNormal", 0.14788315928312,
			 7.0710678114432))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_mediationEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.199131680435585, 0.0699782263826541, -0.0645767270264656, "contGamma",
			 "contNormal", "", "<unicode>", "", 0.346888279557876, 0.0686517479252027,
			 -0.940642139175, -0.0207692258850074, 0.0237283785711593, 0.00147957634307592,
			 "contGamma", "debCollin1", "contNormal", "<unicode>", "<unicode>",
			 0.89629716920239, 0.0113516382972234, 0.130340335406725))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_pathCoefficientsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.199131680435585, 0.0699782263826541, -0.0645767270264656, "contGamma",
			 "<unicode>", 0.346888279557876, "contNormal", 0.0686517479252027,
			 -0.940642139175, -2.65809965637566, 2.32566023372822, -0.166219711323718,
			 "debCollin1", "<unicode>", 0.895982174641171, "contNormal",
			 1.27139068100617, -0.130738500609564, 0.0859003151350918, 0.895699802245546,
			 0.490800058690319, "facGenderm", "<unicode>", 0.017512166892969,
			 "contNormal", 0.206585297867218, 2.37577438354678, -0.0193398290769331,
			 0.00153717100114809, -0.00890132903789248, "contGamma", "<unicode>",
			 0.0946545081957866, "debCollin1", 0.00532586319002703, -1.67134016032569,
			 -0.0368533470074327, 0.0268102220957272, -0.00502156245585276,
			 "facGenderm", "<unicode>", 0.757176711327476, "debCollin1",
			 0.0162410048361424, -0.309190379937446))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_totalEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.19582260917386, 0.0696283078070808, -0.0630971506833897, "Total",
			 0.351461078413813, 0.0677183149983326, -0.931759017998946, -0.0207692258850074,
			 0.0237283785711593, 0.00147957634307592, "Total indirect", 0.89629716920239,
			 0.0113516382972234, 0.130340335406725))



	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_conceptPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "conceptual-path-plot-factor-confounder_M_Y")



	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_statPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "statistical-path-plot-factor-confounder_M_Y")

})
test_that("Test that model number confounder_moderator - continuous works", {
 
options <- jaspTools::analysisOptions("ClassicProcess")
options$dependent <- "contNormal"
options$covariates <- list("contGamma", "contcor1", "contcor2", "debCollin1")
options$factors <- list("facGender", "facExperim")
options$statisticalPathPlotsCovariances <- TRUE
options$statisticalPathPlotsResidualVariances <- TRUE
options$errorCalculationMethod <- "standard"
options$naAction <- "fiml"
options$emulation <- "lavaan"
options$estimator <- "default"
options$moderationProbes <- list(list(probePercentile = 16, value = "16"), list(probePercentile = 50, 
    value = "50"), list(probePercentile = 84, value = "84"))
options$pathPlotsLegend <- TRUE
options$pathPlotsColorPalette <- "colorblind"
options$processModels <- list(list(conceptualPathPlot = TRUE, independentCovariances = TRUE, 
    inputType = "inputVariables", mediationEffects = TRUE, mediatorCovariances = TRUE, 
    modelNumber = 1, modelNumberCovariates = list(), modelNumberIndependent = "", 
    modelNumberMediators = list(), modelNumberModeratorW = "", 
    modelNumberModeratorZ = "", name = "Model 1", pathCoefficients = TRUE, 
    processRelationships = list(list(processDependent = "contNormal", 
        processIndependent = "contGamma", processType = "moderators", 
        processVariable = "contcor1"), list(processDependent = "contNormal", 
        processIndependent = "contGamma", processType = "confounders", 
        processVariable = "contcor2")), residualCovariances = TRUE, 
    statisticalPathPlot = TRUE, totalEffects = TRUE, localTests = FALSE, 
    localTestType = "cis", localTestBootstrap = FALSE, localTestBootstrapSamples = 1000))
set.seed(1)
results <- jaspTools::runAnalysis("ClassicProcess", "debug", options)



	table <- results[["results"]][["modelSummaryTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(1673.68391243829, 1715.3666354141, 4, "Model 1", 100, -820.841956219143,
			 5))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_covariancesTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(0.424979979846172, 0.896765717657169, 0.660872848751671, "contcor2",
			 "<unicode>", 3.99671657991263e-08, "contcor1", 0.120355716108149,
			 5.4909967729146, 0.732635391767718, 1.29452673849026, 1.01358106512899,
			 "contcor1", "<unicode>", 1.53765888910584e-12, "contcor1", 0.14334226321368,
			 7.071055265941, 0.721542494460771, 1.27492599462207, 0.998234244541421,
			 "contcor2", "<unicode>", 1.53765888910584e-12, "contcor2", 0.141171854311181,
			 7.07105711270919, 1.67248035663196, 2.95517833111797, 2.31382934387497,
			 "contGamma", "<unicode>", 1.53743684450092e-12, "contGamma",
			 0.32722488387638, 7.0710678126456, 0.770797942061193, 1.36195643032467,
			 1.06637718619293, "contNormal", "<unicode>", 1.53743684450092e-12,
			 "contNormal", 0.150808507943631, 7.07106781131685, 4.72565231396662,
			 8.3499493673052, 6.53780084063591, "contGamma:contcor1", "<unicode>",
			 1.53721479989599e-12, "contGamma:contcor1", 0.924582564252856,
			 7.07108385276444))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_mediationEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.396528663809054, 0.156057671983207, 16, -0.120235495912924,
			 "contcor2", "contNormal", "", "<unicode>", "", 0.393701114822503,
			 0.140968492316949, -0.85292460702914, -0.0206079744902215, 0.0187008168621928,
			 50, -0.00095357881401436, "contcor2", "contGamma", "contNormal",
			 "<unicode>", "<unicode>", 0.924241577037212, 0.0100279371617226,
			 -0.0950922207265357, -0.0132920341139206, 0.0180760774799312,
			 84, 0.00239202168300531, "contcor2", "contGamma", "contNormal",
			 "<unicode>", "<unicode>", 0.765001164933273, 0.00800221632674874,
			 0.298919897355134, -0.0215739037623553, 0.0336605425836526,
			 "", 0.00604331941064863, "contcor2", "contGamma", "contNormal",
			 "<unicode>", "<unicode>", 0.668004923764089, 0.014090678905758,
			 0.428887738558792))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_pathCoefficientsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.157440020005962, 0.112045981442429, -0.0226970192817661, "contGamma",
			 "<unicode>", 0.741286968684332, "contNormal", 0.0687476921958929,
			 -0.330149544759875, -0.0550997913198914, 0.673135661341931,
			 0.30901793501102, "contcor1", "<unicode>", 0.0962375589460767,
			 "contNormal", 0.185777763878839, 1.66337417653792, -0.172199509107978,
			 0.106681289023578, -0.0327591100422003, "contGamma:contcor1",
			 "<unicode>", 0.64518633527201, "contNormal", 0.0711443680423039,
			 -0.460459639232737, -0.396528663809054, 0.156057671983207, -0.120235495912924,
			 "contcor2", "<unicode>", 0.393701114822503, "contNormal", 0.140968492316949,
			 -0.85292460702914, -0.403237788237695, 0.193560880019057, -0.104838454109319,
			 "contcor2", "<unicode>", 0.491071197065801, "contGamma", 0.152247355809654,
			 -0.688606074974417))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_totalEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.395742508773221, 0.153364359319345, 16, -0.121189074726938,
			 "Total", 0.386963823664923, 0.140080856695289, -0.865136590294808,
			 -0.395397392394023, 0.159710443934186, 50, -0.117843474229918,
			 "Total", 0.405319255104091, 0.14161174406949, -0.832158907470919,
			 -0.396174412496076, 0.167790059491526, 84, -0.114192176502275,
			 "Total", 0.427363383697888, 0.143871131417741, -0.79371153460043,
			 -0.396528663809054, 0.156057671983207, -0.120235495912924, "Total indirect",
			 0.393701114822503, 0.140968492316949, -0.85292460702914))



	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_conceptPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "conceptual-path-plot-continuous-confounder_moderator")



	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_statPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "statistical-path-plot-continuous-confounder_moderator")

})
test_that("Test that model number confounder_moderator - factor works", {
 
options <- jaspTools::analysisOptions("ClassicProcess")
options$dependent <- "contNormal"
options$covariates <- list("contGamma", "contcor1", "contcor2", "debCollin1")
options$factors <- list("facGender", "facExperim")
options$statisticalPathPlotsCovariances <- TRUE
options$statisticalPathPlotsResidualVariances <- TRUE
options$errorCalculationMethod <- "standard"
options$naAction <- "fiml"
options$emulation <- "lavaan"
options$estimator <- "default"
options$moderationProbes <- list(list(probePercentile = 16, value = "16"), list(probePercentile = 50, 
    value = "50"), list(probePercentile = 84, value = "84"))
options$pathPlotsLegend <- TRUE
options$pathPlotsColorPalette <- "colorblind"
options$processModels <- list(list(conceptualPathPlot = TRUE, independentCovariances = TRUE, 
    inputType = "inputVariables", mediationEffects = TRUE, mediatorCovariances = TRUE, 
    modelNumber = 1, modelNumberCovariates = list(), modelNumberIndependent = "", 
    modelNumberMediators = list(), modelNumberModeratorW = "", 
    modelNumberModeratorZ = "", name = "Model 1", pathCoefficients = TRUE, 
    processRelationships = list(list(processDependent = "contNormal", 
        processIndependent = "contGamma", processType = "moderators", 
        processVariable = "facExperim"), list(processDependent = "contNormal", 
        processIndependent = "contGamma", processType = "confounders", 
        processVariable = "facGender")), residualCovariances = TRUE, 
    statisticalPathPlot = TRUE, totalEffects = TRUE, localTests = FALSE, 
    localTestType = "cis", localTestBootstrap = FALSE, localTestBootstrapSamples = 1000))
set.seed(1)
results <- jaspTools::runAnalysis("ClassicProcess", "debug", options)



	table <- results[["results"]][["modelSummaryTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(1330.18808500503, 1371.87080798084, 4, "Model 1", 100, -649.094042502515,
			 5))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_covariancesTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.00962232505003103, 0.0896223044751036, 0.0399999897125363,
			 "facGenderm", "<unicode>", 0.114128642420644, "facExperimexperimental",
			 0.0253179727556128, 1.57990491966497, 0.180704798230636, 0.319295154415572,
			 0.249999976323104, "facExperimexperimental", "<unicode>", 1.53743684450092e-12,
			 "facExperimexperimental", 0.0353553323627676, 7.07106848149382,
			 0.180704798024821, 0.319295153694623, 0.249999975859722, "facGenderm",
			 "<unicode>", 1.53743684450092e-12, "facGenderm", 0.0353553322313535,
			 7.07106849467021, 1.64852433533026, 2.91284939447801, 2.28068686490414,
			 "contGamma", "<unicode>", 1.53743684450092e-12, "contGamma",
			 0.322537829552119, 7.07106781263808, 0.728706145775116, 1.2875826035478,
			 1.00814437466146, "contNormal", "<unicode>", 1.53743684450092e-12,
			 "contNormal", 0.142573144757003, 7.07106781140099, 1.54316182261394,
			 2.72667971047313, 2.13492076654354, "contGamma:facExperimexperimental",
			 "<unicode>", 1.53743684450092e-12, "contGamma:facExperimexperimental",
			 0.301923376448401, 7.07106813542274))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_mediationEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(0.108832957868417, 0.914012147270688, 0.511422552569552, 0, "facGenderm",
			 "contNormal", "", "<unicode>", "", 0.0127813022805476, 0.205406628834362,
			 2.48980549202216, -0.198988505343462, 0.0527669505225173, -0.0731107774104725,
			 1, "facGenderm", "contGamma", "contNormal", "<unicode>", "<unicode>",
			 0.254969127608045, 0.0642245107185118, -1.1383625440279, -0.0618215513880583,
			 0.132974655309278, 0.0355765519606098, "", "facGenderm", "contGamma",
			 "contNormal", "<unicode>", "<unicode>", 0.474043852370205, 0.0496938230074287,
			 0.715914973080085))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_pathCoefficientsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(-0.346197792155774, -0.0018929023468503, -0.174045347251312, "contGamma",
			 "<unicode>", 0.047533574653857, "contNormal", 0.0878344940327364,
			 -1.98151477011348, -1.19662353784035, 0.147938482939316, -0.524342527450518,
			 "facExperimexperimental", "<unicode>", 0.126347506315482, "contNormal",
			 0.343006818335796, -1.52866502769399, -0.00348418129364847,
			 0.520959843630077, 0.258737831168214, "contGamma:facExperimexperimental",
			 "<unicode>", 0.0531227601381636, "contNormal", 0.133789199459907,
			 1.93392166342808, 0.108832957868417, 0.914012147270688, 0.511422552569552,
			 "facGenderm", "<unicode>", 0.0127813022805476, "contNormal",
			 0.205406628834362, 2.48980549202216, -0.171917887663199, 1.0120526981032,
			 0.42006740522, "facGenderm", "<unicode>", 0.16429436342417,
			 "contGamma", 0.302038862730491, 1.39077270197122))



	table <- results[["results"]][["parEstContainer"]][["collection"]][["parEstContainer_Model 1"]][["collection"]][["parEstContainer_Model 1_totalEffectsTable"]][["data"]]
	jaspTools::expect_equal_tables(table,
		list(0.0256784470944819, 0.850945103223677, 0.43831177515908, 0, "Total",
			 0.037348512364032, 0.210531076754163, 2.08193384994129, 0.13633783786735,
			 0.957660371192974, 0.546999104530162, 1, "Total", 0.00903666574412432,
			 0.20952490448909, 2.61066390109555, 0.108832957868417, 0.914012147270688,
			 0.511422552569552, "Total indirect", 0.0127813022805476, 0.205406628834362,
			 2.48980549202216))



	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_conceptPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "conceptual-path-plot-factor-confounder_moderator")



	plotName <- results[["results"]][["pathPlotContainer"]][["collection"]][["pathPlotContainer_Model 1"]][["collection"]][["pathPlotContainer_Model 1_statPathPlot"]][["data"]]
	testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
	jaspTools::expect_equal_plots(testPlot, "statistical-path-plot-factor-confounder_moderator")

})
